SistemaACOPUS/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import reverse_lazy
from django.contrib.auth import views as auth_views
from .forms import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.proyecto.urls')),
    path('',include('apps.usuario.urls')),
    path('accounts/', include('django.contrib.auth.urls')),

    path('reset_password/',
         auth_views.PasswordResetView.as_view(template_name="accounts/password_reset.html"),
         name="reset_password"),

    path('reset_password_sent/', 
        auth_views.PasswordResetDoneView.as_view(template_name="accounts/password_reset_sent.html"), 
        name="password_reset_done"),

    path('reset/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(template_name="accounts/password_reset_form.html", form_class=FormularioContraOlvidada), 
        name="password_reset_confirm"),

    path('reset_password_complete/', 
        auth_views.PasswordResetCompleteView.as_view(template_name="accounts/password_reset_done.html"), 
        name="password_reset_complete"),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='accounts/password_change.html', form_class=FormularioCambioContraseña), 
        name='password_change'),

    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='accounts/password_change_done.html'), 
        name='password_change_done'),

]

'''
1 - Submit email form                         //PasswordResetView.as_view()
2 - Email sent success message                //PasswordResetDoneView.as_view()
3 - Link to password Rest form in email       //PasswordResetConfirmView.as_view()
4 - Password successfully changed message     //PasswordResetCompleteView.as_view()
5 - Password change                           //PasswordChangeDoneView.as_view()
'''

apps/proyecto/urls.py
from django.urls import path, include
from .views import *
from django.contrib.auth.decorators import login_required

from django.conf import settings
from django.conf.urls.static import static 
 
app_name = 'evaluacionCliente'

urlpatterns = [
    
    # URL de base 
    path('',index),
    path('evaluacionCliente/index/',index, name='index'),

    # URL envio de correo
    path('evaluacionCliente/send_email/<str:agencia>/<str:departamento>/<str:comite>/', login_required(enviarEmail), name='send_email'),
    path('evaluacionCliente/listar_empleado_correo/', login_required(listarEmpleadosCorreo), name='listar_empleado_correo'),        
    path('evaluacionCliente/filtrarEmpleadosCorreo/', login_required(filtrarEmpleadosCorreo), name="filtrar_empleados_correo"),
    path('evaluacionCliente/enviar_correo/<str:agencia>/<str:departamento>/<str:comite>/', login_required(enviarCorreo), name="enviar_correo"),
    path('evaluacionCliente/confirmar_invitacion/', login_required(confirmarInvitacion), name="confirmar_invitacion"),

	#URLs para Departamento
    path('evaluacionCliente/crear_departamento/', login_required(crearDepartamento), name='crear_departamento'),
    path('evaluacionCliente/listar_departamento/', login_required(listarDepartamento), name='listar_departamento'),
    path('evaluacionCliente/editar_departamento/<codigo_departamento>/', login_required(editarDepartamento), name='editar_departamento'),
    path('evaluacionCliente/eliminar_departamento/<pk>/', login_required(eliminarDepartamento.as_view()), name='eliminar_departamento'),

	#URLs para Comites
    path('evaluacionCliente/crear_comite/', login_required(crearComite), name='crear_comite'),
    path('evaluacionCliente/listar_comite/', login_required(listarComite), name='listar_comite'),
    path('evaluacionCliente/editar_comite/<id_comite>/', login_required(editarComite), name='editar_comite'),
    path('evaluacionCliente/eliminar_comite/<pk>/', login_required(eliminarComite.as_view()), name='eliminar_comite'),

	#URLs para Agenciaa
    path('evaluacionCliente/crear_agencia/', login_required(crearAgencia), name='crear_agencia'),
    path('evaluacionCliente/listar_agencia/', login_required(listarAgencia), name='listar_agencia'),    
    path('evaluacionCliente/editar_agencia/<codigo_agencia>/', login_required(editarAgencia), name='editar_agencia'),
    path('evaluacionCliente/eliminar_agencia/<pk>/', login_required(eliminarAgencia.as_view()), name='eliminar_agencia'),

    #URLs para Actividades
    path('evaluacionCliente/crear_actividad/', login_required(crearActividad), name='crear_actividad'),
    path('evaluacionCliente/listar_actividad/', login_required(listarActividad), name='listar_actividad'),    
    path('evaluacionCliente/editar_actividad/<id_actividad>/', login_required(editarActividad), name='editar_actividad'),
    path('evaluacionCliente/eliminar_actividad/<pk>/', login_required(eliminarActividad.as_view()), name='eliminar_actividad'),

    #URLs para Empleados
    path('evaluacionCliente/crear_empleado/', login_required(crearEmpleado), name='crear_empleado'),
    path('evaluacionCliente/listar_empleados/', login_required(listarEmpleados), name='listar_empleados'),    
    path('evaluacionCliente/editar_empleado/<id_empleado>/', login_required(editarEmpleado), name='editar_empleado'),
    path('evaluacionCliente/eliminar_empleado/<pk>/', login_required(eliminarEmpleado.as_view()), name='eliminar_empleado'),
    path('evaluacionCliente/filtrarEmpleados/', login_required(filtrarEmpleados), name="filtrar_empleados"),
    path('evaluacionCliente/reporteEmpleadosPDF/<str:agencia>/<str:departamento>/<str:comite>/', login_required(reporteEmpleadosPDF), name="reporte_empleadosPDF"),
    path('evaluacionCliente/exportarEmpleadosCSV/<str:agencia>/<str:departamento>/<str:comite>/', login_required(exportarEmpleados), name="reporte_empleadosCSV"),

    #URLs para Encuesta Cliente
    path('evaluacionCliente/listar_encuesta/', login_required(listarEncuesta), name='listar_encuesta'),
    path('evaluacionCliente/listar_encuesta/Agencia/', login_required(consultarAgencia), name='consultar_agencia'),
    path('evaluacionCliente/listar_encuesta/Agencia2/<str:codigoAgencia>/', login_required(consultarAgencia2), name='consultar_agencia2'),
    path('evaluacionCliente/listar_encuesta/Encuesta/<str:codigoAgencia>', login_required(consultarEncuesta), name='consultar_encuesta'),
    path('evaluacionCliente/listar_encuesta/Encuesta2/<str:codigoAgencia>/<str:tituloEncuesta>/', login_required(consultarEncuesta2), name='consultar_encuesta2'),
    path('evaluacionCliente/listar_encuesta/Preguntas/<str:codigoAgencia>/<str:tituloEncuesta>/', login_required(AgregarPreguntasEncuestaCliente), name='agregar_preguntas_encuesta_cliente'),

    path('evaluacionCliente/crear_encuesta/<str:codigoAgencia>/', login_required(crearEncuesta), name='crear_encuesta'),
    path('evaluacionCliente/editar_encuesta/<int:idEncuesta>/', login_required(editarEncuesta), name='editar_encuesta'),
    path('evaluacionCliente/eliminar_encuesta/<int:idEncuesta>/', login_required(eliminarEncuesta), name='eliminar_encuesta'),

    path('evaluacionCliente/editar_informacion_encuesta/<int:idEncuesta>/', login_required(editarInfEncuesta), name='editar_inf_encuesta'),

    path('evaluacionCliente/contestar_encuesta/', contestarEncuesta, name='contestar_encuesta'),
    path('evaluacionCliente/encuesta/Agencia/', consultarAgenciaEncuesta, name='consultar_agencia_encuesta'),
    path('evaluacionCliente/encuesta/Encuesta/<str:codigoAgencia>', consultarEncuestaCliente, name='consultar_encuesta_cliente'),
    path('evaluacionCliente/encuesta/Encuesta2/<str:codigoAgencia>', consultarEncuestaCliente2, name='consultar_encuesta2'),
    path('evaluacionCliente/encuesta/Encuesta22/<str:codigoAgencia>/<str:tituloEncuesta>', consultarEncuestaCliente22, name='consultar_encuesta22'),
    path('evaluacionCliente/encuesta/Respuesta/<str:codigoAgencia>/<str:tituloEncuesta>/<str:descripcionPregunta>/<int:contador>/', contestarEncuestaCliente, name='contestar_encuesta_cliente'),

    path('evaluacionCliente/Resultados/listar_agencia/', login_required(listarRespuestasEncuesta), name='listar_respuestas_encuesta'),
    path('evaluacionCliente/Resultados/listar_encuesta/', login_required(consultarRespuestasAgenciaCliente), name='consultar_agencia_respuestas_cliente'),
    path('evaluacionCliente/Resultados/listar_resultados/<str:codigoAgencia>', login_required(consultarRespuestasEncuestaCliente), name='consultar_respuestas_encuesta_cliente'),


    #URLs para Encuesta Personal
    path('evaluacionCliente/listar_encuesta_personal/', login_required(listarEncuestaPersonal), name='listar_encuesta_personal'),
    path('evaluacionCliente/listar_encuesta_personal/Actividad/', login_required(consultarActividadPersonal), name='consultar_actividad_personal'),
    path('evaluacionCliente/listar_encuesta_personal/Actividad2/<str:idActividad>/', login_required(consultarActividad2Personal), name='consultar_actividad2_personal'),
    path('evaluacionCliente/listar_encuesta_personal/Encuesta/<str:idActividad>', login_required(consultarEncuestaPersonal), name='consultar_encuesta_personal'),
    path('evaluacionCliente/listar_encuesta_personal/Encuesta2/<str:idActividad>/<str:tituloEncuesta>/', login_required(consultarEncuesta2Personal), name='consultar_encuesta2_personal'),
    path('evaluacionCliente/listar_encuesta_personal/Preguntas/<str:idActividad>/<str:tituloEncuesta>/', login_required(AgregarPreguntasEncuestaPersonal), name='agregar_preguntas_encuesta_personal'),

    path('evaluacionCliente/crear_encuesta_personal/<str:idActividad>/', login_required(crearEncuestaPersonal), name='crear_encuesta_personal'),
    path('evaluacionCliente/editar_encuesta_personal/<int:idEncuesta>/', login_required(editarEncuestaPersonal), name='editar_encuesta_personal'),
    path('evaluacionCliente/eliminar_encuesta_personal/<int:idEncuesta>/', login_required(eliminarEncuestaPersonal), name='eliminar_encuesta_personal'),
    
    path('evaluacionCliente/editar_informacion_encuesta_personal/<int:idEncuesta>/', login_required(editarInfEncuestaPersonal), name='editar_inf_encuesta_personal'),

    path('evaluacionCliente/contestar_encuesta_personal/', contestarEncuestaPersonal, name='contestar_encuesta_personal'),
    path('evaluacionCliente/encuestaPersonal/Actividad/', consultarActividadEncuestaDePersonal, name='consultar_actividad_encuesta_de_personal'),
    path('evaluacionCliente/encuestaPersonal/Encuesta/<str:idActividad>', consultarEncuestaDePersonal, name='consultar_encuesta_de_personal'),
    path('evaluacionCliente/encuestaPersonal/Encuesta2/<str:idActividad>', consultarEncuestaDePersonal2, name='consultar_encuesta_de_personal2'),
    path('evaluacionCliente/encuestaPersonal/Encuesta22/<str:idActividad>/<str:tituloEncuestaPersonal>', consultarEncuestaDePersonal22, name='consultar_encuesta_de_personal22'),
    path('evaluacionCliente/encuestaPersonal/Respuesta/<str:idActividad>/<str:tituloEncuesta>/<str:descripcionPregunta>/<int:contador>/', contestarEncuestaDePersonal, name='contestar_encuesta_de_personal'),

    path('evaluacionCliente/Resultados/listar_actividad/', login_required(listarRespuestasEncuestaPersonal), name='listar_respuestas_encuesta_personal'),
    path('evaluacionCliente/Resultados/listar_encuesta_personal/', login_required(consultarRespuestasActividadPersonal), name='consultar_actividad_respuestas_personal'),
    path('evaluacionCliente/Resultados/listar_resultados_encuesta/<str:idActividad>', login_required(consultarRespuestasEncuestaPersonal), name='consultar_respuestas_encuesta_personal'),

    #URLs para Reportes de Respuesta
    path('evaluacionCliente/Resultados/respuestas_encuestas_cliente/', login_required(reporteRespuestasEncuestaCliente), name='respuestas_encuestas_cliente'),

apps/usuario/urls.py
from django.urls import path, include
from .views import *
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView
from apps.usuario.views import Login, logoutUsuario
from apps.usuario.views import ListadoUsuario, RegistrarUsuario, RegistrarUsuarioLogin, InicioListadoUsuario, EditarUsuario, EliminarUsuario


app_name='usuario'

urlpatterns=[
    #URL para el menu de inicio
    path('', Login.as_view()),
    path('usuario/index/',index, name='index'),

    path('accounts/login/',Login.as_view(), name='login'),
    path('logout/',login_required(logoutUsuario), name='logout'),
    
    path('inicio_usuarios/', login_required(InicioListadoUsuario.as_view()), name='inicio_usuarios'),   
    path('listado_usuarios/', login_required(ListadoUsuario.as_view()), name='listar_usuarios'),
    path('registrar_usuario/', login_required(RegistrarUsuario.as_view()), name='registrar_usuario'),
    path('registrar_usuario/login', RegistrarUsuarioLogin.as_view(), name='registrar_usuario_login'),
    path('actualizar_usuario/<int:pk>/',EditarUsuario.as_view(), name = 'actualizar_usuario'),
    path('eliminar_usuario/<int:pk>/',EliminarUsuario.as_view(), name='eliminar_usuario'),
    
]

apps/usuario/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser,BaseUserManager
from apps.usuario.models import *

roles=[
    ('ADM', 'Administrador'),
]

class UsuarioManager(BaseUserManager):
    def create_user(self, email,username,nombres, apellidos, password=None):
        if not email:
            raise ValueError('El usuario debe tener un correo electronico')

        user = self.model(
            username = username,
            email = self.normalize_email(email),
            nombres = nombres,    
            apellidos=apellidos,
        )
        
        user.set_password(password)
        user.save()
        return user
    
    def create_superuser(self,username,email,nombres,apellidos, password):
        user=self.create_user(
            email,
            username = username,
            nombres = nombres,
            apellidos=apellidos,
            password=password,
        )

        user.usuario_administrador= True
        user.save()
        return user


class Usuario(AbstractBaseUser):
    username = models.CharField('Nombre de usuario',unique = True, max_length=15, blank=False)
    email = models.EmailField('Correo Electrónico', max_length=254,unique = True, blank=False)
    nombres = models.CharField('Nombres', max_length=200, null = False, blank=False)
    apellidos = models.CharField('Apellidos', max_length=200, null = False, blank=False)
    imagen = models.ImageField('Imagen de Perfil', upload_to='perfil/', max_length=200,blank = True,null = True)
    is_active = models.BooleanField(default = True)
    usuario_administrador = models.BooleanField(default = False)
    rol=models.CharField(max_length=3,null=False, blank=False,choices=roles,default='ADM')    

    objects = UsuarioManager()

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email','nombres', 'apellidos']

    def __str__(self):
        return f'{self.nombres},{self.apellidos}'

    def save(self, *args, **kwargs):

        if self.usuario_administrador == True:
            self.rol = 'ADM'

        super().save(*args, **kwargs)

    def has_perm(self, perm,obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    @property
    def is_staff(self):
        return self.usuario_administrador

templates/usuario/crear_usuario.html
{% extends 'base/base.html' %}

{% load static %}

<title>{% block title %} Registrar Usuario {% endblock %}</title>

<!-- CSS y Bootstrap -->
<link rel = "stylesheet" href = "{% static 'css/bootstrap.min.css' %}">
{% block content %}
</br>
<div class="card">
    <div class="card-header">
        <h2 align="center" class="form-titulo" style ="margin-left: 5px;">Registro de Usuarios</h2>
    </div>
    <div class="card-body">
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <div class="">
                <input type="submit" class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent btn-buscar" name="submit" value="Registrar">
                <a href="{% url 'usuario:listar_usuarios' %}"><input type="button" href="{% url 'usuario:listar_usuarios' %}" class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent btn-buscar" name="submit" value="Cancelar"></a>
            </div>
        </form>
    </div>
</div>
{% endblock %}

templates/usuario/crear_usuario_login.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
 {% block head %}
 	<title>{% block title %} Registrar Usuario {% endblock %}</title>

	{% block static %}
	<meta content="width=device-width, initial-scale=1.0" name="viewport">
	<!-- Favicon -->
	<link type="image/x-icon" href="{% static 'img/favAgronomia.png'%}" rel="icon">
	<!-- Enlaces -->
	<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,700,700i|Montserrat:300,400,500,700" rel="stylesheet">
	<script type="text/javascript" src="https://code.jquery.com/jquery-3.4.1.js"></script>
	<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
	<script src="https://code.jquery.com/jquery-3.4.1.js" integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=" crossorigin="anonymous"></script>
	<!-- Librerias -->
	<link rel = "stylesheet" href = "{% static 'lib/bootstrap/css/bootstrap.min.css' %}">
	<link rel = "stylesheet" href = "{% static 'lib/animate/animate.min.css' %}">
	<link rel = "stylesheet" href = "{% static 'lib/ionicons/css/ionicons.min.css' %}">
	<script src = "{% static 'lib/jquery/jquery.min.js' %}"></script>
	<script src = "{% static 'lib/jquery/jquery-migrate.min.js' %}"></script>
	<script src = "{% static 'lib/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
	<!-- CSS y Bootstrap -->
	<link rel = "stylesheet" href = "{% static 'css/style.css' %}">
	<link rel = "stylesheet" href = "{% static 'css/bootstrap.min.css' %}">
	<link rel = "stylesheet" href = "{% static 'css/archivo.css' %}">
	<link rel = "stylesheet" href = "{% static 'css/estilos_sec_not.css' %}">
	<link rel = "stylesheet" type = "text/css" href = "{% static 'css/jquery-ui.css' %}"/>
	<link rel = "stylesheet" type = "text/css" href = "{% static 'css/jquery.dataTables.min.css' %}"/>
	<!-- JavaScript -->
	<script type = "text/javascript" src = "{% static 'js/bootstrap.min.js' %}"></script>
	<script type = "text/javascript" src = "{% static 'js/jquery.js' %}" charset="UTF-8"></script>
	<script type = "text/javascript" src = "{% static 'js/bootstrap.min.js' %}" charset="UTF-8"></script>
	<script type = "text/javascript" src = "{% static 'js/jquery-ui.js' %}"></script>
	<script type = "text/javascript" src = "{% static 'js/jquery.dataTables.min.js' %}"></script>
    <script type = "text/javascript" src = "{% static 'js/main.js' %}"></script>
	{% endblock %}

{% endblock %}
</head>

<body>
	<header id="header">
		<div class="container-fluid navbar navbar-light">
			<div id="logo" class="pull-left">
				<a  href="{% url 'usuario:index' %}"><img src="{% static 'img/logoUPSAgro.png' %}" class ="imglogo"></a>
				<h1 style="color:white;">Servicio Social - Agronomia.</h1>
			</div>
		</div>
	</header>

  <section>
  </br></br></br></br>
    <div class="modal-content">
        <div class="modal-body">
            <div class="panel-body" align="center">
                <h2 align="center" class="form-titulo" style ="margin-left: 5px;">Registro de Usuarios</h2>
            
                <form method="POST">
                    {% csrf_token %}
                    <div class="row-xx">
                        <div class="col-5 col-sm-15">
                            {{ form.as_p }}
                        </div>
                    </div>
                    
                    <div class="col-lg-12 text-center">
                        <input type="submit" class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent btn-buscar" name="submit" value="Registrar">
                        <a href="{% url 'usuario:login' %}"><input type="button" href="{% url 'usuario:login' %}" class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent btn-buscar" name="submit" value="Cancelar"></a>
                    </div>
                </form>
            </div>
        </div>
    </div>
    
  </section>

  {% block js %}

	{% endblock %}

</body>

	<!-- Para el modal de la Ventana Flotante-->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
	<script src="https://code.jquery.com/jquery-1.12.0.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script>
       $(document).ready(function()
       {
          $("#mostrarmodal").modal("show");
       });
    </script>

</html>







{% comment %} {% load static %}

<title>{% block title %} Registrar Usuario {% endblock %}</title>

<!-- CSS y Bootstrap -->
<link rel = "stylesheet" href = "{% static 'css/bootstrap.min.css' %}">
{% block content %}
</br>
<div class="card">
    <div class="card-header">
        <h2 align="center" class="form-titulo" style ="margin-left: 5px;">Registro de Usuarios</h2>
    </div>
    <div class="card-body">
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <div class="">
                <input type="submit" class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent btn-buscar" name="submit" value="Registrar">
                <a href="{% url 'usuario:login' %}"><input type="button" href="{% url 'usuario:login' %}" class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent btn-buscar" name="submit" value="Cancelar"></a>
            </div>
        </form>
    </div>
</div>
{% endblock %} {% endcomment %}

templates/usuario/index_usuario.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
 {% block head %}
 	<title>{% block title %} Sistema Servicio Social {% endblock %}</title>

	{% block static %}

	<meta content="width=device-width, initial-scale=1.0" name="viewport">

	<!-- Favicon -->
	<link type="image/x-icon" href="{% static 'img/favAgronomia.png'%}" rel="icon">

	<!-- Enlaces -->
	<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,700,700i|Montserrat:300,400,500,700" rel="stylesheet">
	<script type="text/javascript" src="https://code.jquery.com/jquery-3.4.1.js"></script>
	<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
	<script src="https://code.jquery.com/jquery-3.4.1.js" integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=" crossorigin="anonymous"></script>

	<!-- Librerias -->
	<link rel = "stylesheet" href = "{% static 'lib/bootstrap/css/bootstrap.min.css' %}">
	<link rel = "stylesheet" href = "{% static 'lib/animate/animate.min.css' %}">
	<link rel = "stylesheet" href = "{% static 'lib/ionicons/css/ionicons.min.css' %}">
	<script src = "{% static 'lib/jquery/jquery.min.js' %}"></script>
	<script src = "{% static 'lib/jquery/jquery-migrate.min.js' %}"></script>
	<script src = "{% static 'lib/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

	<!-- CSS y Bootstrap -->
	<link rel = "stylesheet" href = "{% static 'css/style.css' %}">
	<link rel = "stylesheet" href = "{% static 'css/bootstrap.min.css' %}">
	<link rel = "stylesheet" href = "{% static 'css/archivo.css' %}">
	<link rel = "stylesheet" href = "{% static 'css/estilos_sec_not.css' %}">
	<link rel = "stylesheet" type = "text/css" href = "{% static 'css/jquery-ui.css' %}"/>
	<link rel = "stylesheet" type = "text/css" href = "{% static 'css/jquery.dataTables.min.css' %}"/>

	<!-- JavaScript -->
	<script type = "text/javascript" src = "{% static 'js/bootstrap.min.js' %}"></script>
	<script type = "text/javascript" src = "{% static 'js/jquery.js' %}" charset="UTF-8"></script>
	<script type = "text/javascript" src = "{% static 'js/bootstrap.min.js' %}" charset="UTF-8"></script>
	<script type = "text/javascript" src = "{% static 'js/jquery-ui.js' %}"></script>
	<script type = "text/javascript" src = "{% static 'js/jquery.dataTables.min.js' %}"></script>
  	<script type = "text/javascript" src = "{% static 'js/main.js' %}"></script>

	{% endblock %}

{% endblock %}

</head>

<body>
	<header id="header">

		<div class="container-fluid navbar navbar-light">
			<div id="logo" class="pull-left">
				<a  href="{% url 'usuario:index' %}"><img src="{% static 'img/logoUPSAgro.png' %}" class ="imglogo"></a>
				<h1>Servicio Social - Agronomia.</h1>
			</div>

			<div id="logo" class="pull-rigth">
				<input type="button" href="" class="btn-success btn" name="submit" value="{{ user.username }}" disabled style="background-color:transparent; border:none;"></a> 
        <a href="{% url 'usuario:logout' %}" style="text-decoration:none"><input type="button" href="{% url 'usuario:logout' %}" class="btn btn-success btn-sm" name="submit" value="Cerrar Sesi&oacute;n" style="background:green;"></a> 
			</div>

		</div>

		<div class="bot">
			<ul class="nav-menu">
				<a href="{% url 'evaluacionCliente:index' user.username %}" style="text-decoration:none"><input type="button" href="{% url 'evaluacionCliente:index' user.username %}" class="btn btn-success btn-sm" name="submit" value="Comenzar" style="background:green;"></a>
			</ul>
		</div>
	</header>


  <section>
    <div class="container">
      </br></br></br></br></br></br></br>

  		{% block content %}
        </br></br></br></br></br></br></br></br></br></br><img src = "{% static 'img/FondoUPS_Inicio.png' %}">
      {%endblock%}

	  <div class="modal fade" id="mostrarmodal" tabindex="-1" role="dialog" aria-labelledby="basicModal" aria-hidden="true">
			<div class="modal-dialog">
				<div class="modal-content">
				<div class="modal-header">
					<h3><strong><i>Bienvenido al Sistema Gestor de</br>Servicio Social - Agronom&iacute;a</i></strong></h3>
				</div>
				<div class="modal-body">
					<h4><strong>¡Atenci&oacute;n!</strong></h4>
					<i>Porfavor presiona el bot&oacute;n de <strong>Comenzar</strong> </br>para poder iniciar.</i></br>
					</br><img src = "{% static 'img/favAgronomia.png' %}">
			</div>
				<div class="modal-footer">
				<a href="{% url 'evaluacionCliente:index' user.username %}" class="btn btn-Secundary">Comenzar</a>
				</div>
			</div>
		</div>

    </div>
  </section>

  {% block js %}

	{% endblock %}

</body>

	<!-- Para el modal de la Ventana Flotante-->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
	<script src="https://code.jquery.com/jquery-1.12.0.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script>
       $(document).ready(function()
       {
          $("#mostrarmodal").modal("show");
       });
    </script>


</html>