SistemaACOPUS/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import reverse_lazy
from django.contrib.auth import views as auth_views
from .forms import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.proyecto.urls')),
    path('',include('apps.usuario.urls')),
    path('accounts/', include('django.contrib.auth.urls')),

    path('reset_password/',
         auth_views.PasswordResetView.as_view(template_name="accounts/password_reset.html"),
         name="reset_password"),

    path('reset_password_sent/', 
        auth_views.PasswordResetDoneView.as_view(template_name="accounts/password_reset_sent.html"), 
        name="password_reset_done"),

    path('reset/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(template_name="accounts/password_reset_form.html", form_class=FormularioContraOlvidada), 
        name="password_reset_confirm"),

    path('reset_password_complete/', 
        auth_views.PasswordResetCompleteView.as_view(template_name="accounts/password_reset_done.html"), 
        name="password_reset_complete"),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='accounts/password_change.html', form_class=FormularioCambioContraseña), 
        name='password_change'),

    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='accounts/password_change_done.html'), 
        name='password_change_done'),

]

'''
1 - Submit email form                         //PasswordResetView.as_view()
2 - Email sent success message                //PasswordResetDoneView.as_view()
3 - Link to password Rest form in email       //PasswordResetConfirmView.as_view()
4 - Password successfully changed message     //PasswordResetCompleteView.as_view()
5 - Password change                           //PasswordChangeDoneView.as_view()
'''

apps/proyecto/urls.py
from django.urls import path, include
from .views import *
from django.contrib.auth.decorators import login_required

from django.conf import settings
from django.conf.urls.static import static 
 
app_name = 'evaluacionCliente'

urlpatterns = [
    
    # URL de base 
    path('',index),
    path('evaluacionCliente/index/',index, name='index'),

    # URL envio de correo
    path('evaluacionCliente/send_email/<str:agencia>/<str:departamento>/<str:comite>/', login_required(enviarEmail), name='send_email'),
    path('evaluacionCliente/listar_empleado_correo/', login_required(listarEmpleadosCorreo), name='listar_empleado_correo'),        
    path('evaluacionCliente/filtrarEmpleadosCorreo/', login_required(filtrarEmpleadosCorreo), name="filtrar_empleados_correo"),
    path('evaluacionCliente/enviar_correo/<str:agencia>/<str:departamento>/<str:comite>/', login_required(enviarCorreo), name="enviar_correo"),
    path('evaluacionCliente/confirmar_invitacion/', login_required(confirmarInvitacion), name="confirmar_invitacion"),

	#URLs para Departamento
    path('evaluacionCliente/crear_departamento/', login_required(crearDepartamento), name='crear_departamento'),
    path('evaluacionCliente/listar_departamento/', login_required(listarDepartamento), name='listar_departamento'),
    path('evaluacionCliente/editar_departamento/<codigo_departamento>/', login_required(editarDepartamento), name='editar_departamento'),
    path('evaluacionCliente/eliminar_departamento/<pk>/', login_required(eliminarDepartamento.as_view()), name='eliminar_departamento'),

	#URLs para Comites
    path('evaluacionCliente/crear_comite/', login_required(crearComite), name='crear_comite'),
    path('evaluacionCliente/listar_comite/', login_required(listarComite), name='listar_comite'),
    path('evaluacionCliente/editar_comite/<id_comite>/', login_required(editarComite), name='editar_comite'),
    path('evaluacionCliente/eliminar_comite/<pk>/', login_required(eliminarComite.as_view()), name='eliminar_comite'),

	#URLs para Agenciaa
    path('evaluacionCliente/crear_agencia/', login_required(crearAgencia), name='crear_agencia'),
    path('evaluacionCliente/listar_agencia/', login_required(listarAgencia), name='listar_agencia'),    
    path('evaluacionCliente/editar_agencia/<codigo_agencia>/', login_required(editarAgencia), name='editar_agencia'),
    path('evaluacionCliente/eliminar_agencia/<pk>/', login_required(eliminarAgencia.as_view()), name='eliminar_agencia'),

    #URLs para Actividades
    path('evaluacionCliente/crear_actividad/', login_required(crearActividad), name='crear_actividad'),
    path('evaluacionCliente/listar_actividad/', login_required(listarActividad), name='listar_actividad'),    
    path('evaluacionCliente/editar_actividad/<id_actividad>/', login_required(editarActividad), name='editar_actividad'),
    path('evaluacionCliente/eliminar_actividad/<pk>/', login_required(eliminarActividad.as_view()), name='eliminar_actividad'),

    #URLs para Empleados
    path('evaluacionCliente/crear_empleado/', login_required(crearEmpleado), name='crear_empleado'),
    path('evaluacionCliente/listar_empleados/', login_required(listarEmpleados), name='listar_empleados'),    
    path('evaluacionCliente/editar_empleado/<id_empleado>/', login_required(editarEmpleado), name='editar_empleado'),
    path('evaluacionCliente/eliminar_empleado/<pk>/', login_required(eliminarEmpleado.as_view()), name='eliminar_empleado'),
    path('evaluacionCliente/filtrarEmpleados/', login_required(filtrarEmpleados), name="filtrar_empleados"),
    path('evaluacionCliente/reporteEmpleadosPDF/<str:agencia>/<str:departamento>/<str:comite>/', login_required(reporteEmpleadosPDF), name="reporte_empleadosPDF"),
    path('evaluacionCliente/exportarEmpleadosCSV/<str:agencia>/<str:departamento>/<str:comite>/', login_required(exportarEmpleados), name="reporte_empleadosCSV"),

    #URLs para Encuesta Cliente
    path('evaluacionCliente/listar_encuesta/', login_required(listarEncuesta), name='listar_encuesta'),
    path('evaluacionCliente/listar_encuesta/Agencia/', login_required(consultarAgencia), name='consultar_agencia'),
    path('evaluacionCliente/listar_encuesta/Agencia2/<str:codigoAgencia>/', login_required(consultarAgencia2), name='consultar_agencia2'),
    path('evaluacionCliente/listar_encuesta/Encuesta/<str:codigoAgencia>', login_required(consultarEncuesta), name='consultar_encuesta'),
    path('evaluacionCliente/listar_encuesta/Encuesta2/<str:codigoAgencia>/<str:tituloEncuesta>/', login_required(consultarEncuesta2), name='consultar_encuesta2'),
    path('evaluacionCliente/listar_encuesta/Preguntas/<str:codigoAgencia>/<str:tituloEncuesta>/', login_required(AgregarPreguntasEncuestaCliente), name='agregar_preguntas_encuesta_cliente'),

    path('evaluacionCliente/crear_encuesta/<str:codigoAgencia>/', login_required(crearEncuesta), name='crear_encuesta'),
    path('evaluacionCliente/editar_encuesta/<int:idEncuesta>/', login_required(editarEncuesta), name='editar_encuesta'),
    path('evaluacionCliente/eliminar_encuesta/<int:idEncuesta>/', login_required(eliminarEncuesta), name='eliminar_encuesta'),

    path('evaluacionCliente/editar_informacion_encuesta/<int:idEncuesta>/', login_required(editarInfEncuesta), name='editar_inf_encuesta'),

    path('evaluacionCliente/contestar_encuesta/', contestarEncuesta, name='contestar_encuesta'),
    path('evaluacionCliente/encuesta/Agencia/', consultarAgenciaEncuesta, name='consultar_agencia_encuesta'),
    path('evaluacionCliente/encuesta/Encuesta/<str:codigoAgencia>', consultarEncuestaCliente, name='consultar_encuesta_cliente'),
    path('evaluacionCliente/encuesta/Encuesta2/<str:codigoAgencia>', consultarEncuestaCliente2, name='consultar_encuesta2'),
    path('evaluacionCliente/encuesta/Encuesta22/<str:codigoAgencia>/<str:tituloEncuesta>', consultarEncuestaCliente22, name='consultar_encuesta22'),
    path('evaluacionCliente/encuesta/Respuesta/<str:codigoAgencia>/<str:tituloEncuesta>/<str:descripcionPregunta>/<int:contador>/', contestarEncuestaCliente, name='contestar_encuesta_cliente'),

    path('evaluacionCliente/Resultados/listar_agencia/', login_required(listarRespuestasEncuesta), name='listar_respuestas_encuesta'),
    path('evaluacionCliente/Resultados/listar_encuesta/', login_required(consultarRespuestasAgenciaCliente), name='consultar_agencia_respuestas_cliente'),
    path('evaluacionCliente/Resultados/listar_resultados/<str:codigoAgencia>', login_required(consultarRespuestasEncuestaCliente), name='consultar_respuestas_encuesta_cliente'),


    #URLs para Encuesta Personal
    path('evaluacionCliente/listar_encuesta_personal/', login_required(listarEncuestaPersonal), name='listar_encuesta_personal'),
    path('evaluacionCliente/listar_encuesta_personal/Actividad/', login_required(consultarActividadPersonal), name='consultar_actividad_personal'),
    path('evaluacionCliente/listar_encuesta_personal/Actividad2/<str:idActividad>/', login_required(consultarActividad2Personal), name='consultar_actividad2_personal'),
    path('evaluacionCliente/listar_encuesta_personal/Encuesta/<str:idActividad>', login_required(consultarEncuestaPersonal), name='consultar_encuesta_personal'),
    path('evaluacionCliente/listar_encuesta_personal/Encuesta2/<str:idActividad>/<str:tituloEncuesta>/', login_required(consultarEncuesta2Personal), name='consultar_encuesta2_personal'),
    path('evaluacionCliente/listar_encuesta_personal/Preguntas/<str:idActividad>/<str:tituloEncuesta>/', login_required(AgregarPreguntasEncuestaPersonal), name='agregar_preguntas_encuesta_personal'),

    path('evaluacionCliente/crear_encuesta_personal/<str:idActividad>/', login_required(crearEncuestaPersonal), name='crear_encuesta_personal'),
    path('evaluacionCliente/editar_encuesta_personal/<int:idEncuesta>/', login_required(editarEncuestaPersonal), name='editar_encuesta_personal'),
    path('evaluacionCliente/eliminar_encuesta_personal/<int:idEncuesta>/', login_required(eliminarEncuestaPersonal), name='eliminar_encuesta_personal'),
    
    path('evaluacionCliente/editar_informacion_encuesta_personal/<int:idEncuesta>/', login_required(editarInfEncuestaPersonal), name='editar_inf_encuesta_personal'),

    path('evaluacionCliente/contestar_encuesta_personal/', contestarEncuestaPersonal, name='contestar_encuesta_personal'),
    path('evaluacionCliente/encuestaPersonal/Actividad/', consultarActividadEncuestaDePersonal, name='consultar_actividad_encuesta_de_personal'),
    path('evaluacionCliente/encuestaPersonal/Encuesta/<str:idActividad>', consultarEncuestaDePersonal, name='consultar_encuesta_de_personal'),
    path('evaluacionCliente/encuestaPersonal/Encuesta2/<str:idActividad>', consultarEncuestaDePersonal2, name='consultar_encuesta_de_personal2'),
    path('evaluacionCliente/encuestaPersonal/Encuesta22/<str:idActividad>/<str:tituloEncuestaPersonal>', consultarEncuestaDePersonal22, name='consultar_encuesta_de_personal22'),
    path('evaluacionCliente/encuestaPersonal/Respuesta/<str:idActividad>/<str:tituloEncuesta>/<str:descripcionPregunta>/<int:contador>/', contestarEncuestaDePersonal, name='contestar_encuesta_de_personal'),

    path('evaluacionCliente/Resultados/listar_actividad/', login_required(listarRespuestasEncuestaPersonal), name='listar_respuestas_encuesta_personal'),
    path('evaluacionCliente/Resultados/listar_encuesta_personal/', login_required(consultarRespuestasActividadPersonal), name='consultar_actividad_respuestas_personal'),
    path('evaluacionCliente/Resultados/listar_resultados_encuesta/<str:idActividad>', login_required(consultarRespuestasEncuestaPersonal), name='consultar_respuestas_encuesta_personal'),

    #URLs para Reportes de Respuesta
    path('evaluacionCliente/Resultados/respuestas_encuestas_cliente/', login_required(reporteRespuestasEncuestaCliente), name='respuestas_encuestas_cliente'),

apps/usuario/urls.py
from django.urls import path, include
from .views import *
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView
from apps.usuario.views import Login, logoutUsuario
from apps.usuario.views import ListadoUsuario, RegistrarUsuario, RegistrarUsuarioLogin, InicioListadoUsuario, EditarUsuario, EliminarUsuario


app_name='usuario'

urlpatterns=[
    #URL para el menu de inicio
    path('', Login.as_view()),
    path('usuario/index/',index, name='index'),

    path('accounts/login/',Login.as_view(), name='login'),
    path('logout/',login_required(logoutUsuario), name='logout'),
    
    path('inicio_usuarios/', login_required(InicioListadoUsuario.as_view()), name='inicio_usuarios'),   
    path('listado_usuarios/', login_required(ListadoUsuario.as_view()), name='listar_usuarios'),
    path('registrar_usuario/', login_required(RegistrarUsuario.as_view()), name='registrar_usuario'),
    path('registrar_usuario/login', RegistrarUsuarioLogin.as_view(), name='registrar_usuario_login'),
    path('actualizar_usuario/<int:pk>/',EditarUsuario.as_view(), name = 'actualizar_usuario'),
    path('eliminar_usuario/<int:pk>/',EliminarUsuario.as_view(), name='eliminar_usuario'),
    
]

templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">

<head>
{% block head %}
	<title>{% block title %} Inicio {% endblock title %}</title>


	{% block static %}
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
	<link rel="stylesheet" href="{% static 'css/main.css' %}">
	<link type="image/x-icon" href="{% static './assets/img/logo_acopus2.jpg' %}" rel="icon">

	<script src="https://code.jquery.com/jquery-3.4.1.js" integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=" crossorigin="anonymous"></script>
	<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

	<script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
	<script src="https://cdn.datatables.net/1.10.16/js/dataTables.bootstrap4.min.js"></script>
	

	<!--====== Scripts -->
	<script src="{% static 'js/sweetalert2.min.js' %}"></script>
	<script src="{% static 'js/material.min.js' %}"></script>
	<script src="{% static 'js/ripples.min.js' %}"></script>
	<script src="{% static 'js/jquery.mCustomScrollbar.concat.min.js' %}"></script>
  	<script src="https://cdn.jsdelivr.net/npm/sweetalert2@10"></script>	
	<script src="{% static 'js/main.js' %}"></script>

	<script>
      {% if messages %}
          var html_mensaje = '';
          {% for mensaje in messages %}
              html_mensaje += '{{ mensaje }}';
          {% endfor %}
          notificacionError(html_mensaje);
      {% endif %}

	$(document).ready(function() {
	    $('#bootstrapdatatable').DataTable({
		      	"aLengthMenu": [[5, 10, 25, -1], [5, 10, 25, "Todo"]],
		      	"order": false,
		        "iDisplayLength": 5, 
            language: {           	
                "decimal": "",
                "emptyTable": "No hay información",
                "info": "Mostrando _START_ a _END_ de _TOTAL_ Entradas",
                "infoEmpty": "Mostrando 0 to 0 of 0 Entradas",
                "infoFiltered": "(Filtrado de _MAX_ total entradas)",
                "infoPostFix": "",
                "thousands": ",",
                "lengthMenu": "Mostrar _MENU_ Entradas",
                "loadingRecords": "Cargando...",
                "processing": "Procesando...",
                "search": "Buscar:",
                "zeroRecords": "Sin resultados encontrados",
                "paginate": {
                    "first": "Primero",
                    "last": "Ultimo",
                    "next": "Siguiente",
                    "previous": "Anterior"
              },
            },  	        
	       } 
	    );
	} );

  	</script>

	{% endblock %}
{% endblock %}

  {% block extra_css %}
  {% endblock extra_css %}

</head>

<body>

{% if user.is_authenticated %}

	<!-- SideBar -->
	<section class="full-box cover dashboard-sideBar">
		<div class="full-box dashboard-sideBar-bg btn-menu-dashboard"></div>
		<div class="full-box dashboard-sideBar-ct">


			<!--SideBar Title -->
			<div class="full-box text-uppercase text-center text-titles dashboard-sideBar-title">
				ACOPUS de R.L. <i class="zmdi zmdi-close btn-menu-dashboard visible-xs"></i>
			</div>


			<!-- SideBar User info -->
			<div class="full-box dashboard-sideBar-UserInfo">
				<figure class="full-box" onclick="location.href='{% url 'evaluacionCliente:index' %}'">
					<img src="{% static './assets/img/logo_acopus2.jpg' %}" alt="UserIcon"></figure></br>
					<figcaption class="text-center text-titles"> {{user.username}} </figcaption>
				</figure>
				<ul class="full-box list-unstyled text-center">
					<li>
						<a href="{% url 'password_change' %}">
							<i class="zmdi zmdi-settings"></i>
						</a>
					</li>
					<li>
						<a href="{% url 'usuario:logout' %}" class="btn-exit-system">
							<i class="zmdi zmdi-power"></i>
						</a>
					</li>
				</ul>
			</div>


			<!-- SideBar Menu -->
			<ul class="list-unstyled full-box dashboard-sideBar-Menu">
				
				<li>
					<a href="#!" class="btn-sideBar-SubMenu">
						<i class="zmdi zmdi-account-add zmdi-hc-fw"></i> Usuarios <i class="zmdi zmdi-caret-down pull-right"></i>
					</a>
					<ul class="list-unstyled full-box">
						<li>
							<a href="{% url 'usuario:inicio_usuarios' %}"><i class="zmdi zmdi-account zmdi-hc-fw"></i>Administrar Usuarios</a>
						</li>

					</ul>
				</li>

				<li>
					<a href="#!" class="btn-sideBar-SubMenu">
						<i class="zmdi zmdi-account-add zmdi-hc-fw"></i> Empleados <i class="zmdi zmdi-caret-down pull-right"></i>
					</a>
					<ul class="list-unstyled full-box">
						<li>
							<a href="{% url 'evaluacionCliente:listar_empleados' %}"><i class="zmdi zmdi-account-box zmdi-hc-fw"></i>Administrar Empleados</a>
						</li>

					</ul>
				</li>

				<li>
					<a href="#!" class="btn-sideBar-SubMenu">
						<i class="zmdi zmdi-spellcheck zmdi-hc-fw"></i> Encuesta Clientes <i class="zmdi zmdi-caret-down pull-right"></i>
					</a>
					<ul class="list-unstyled full-box">
						<li>
							<a href="{% url 'evaluacionCliente:listar_encuesta' %}"><i class="zmdi zmdi-font zmdi-hc-fw"></i> Consultar Encuestas Clientes</a>
						</li>
						<li>
							<a href="{% url 'evaluacionCliente:listar_respuestas_encuesta' %}"><i class="zmdi zmdi-format-list-bulleted zmdi-hc-fw"></i>Consultar Resultados Encuesta</a>
						</li>
						<li>
							<a href="{% url 'evaluacionCliente:contestar_encuesta' %}"><i class="zmdi zmdi-check-all zmdi-hc-fw"></i> Contestar Encuestas Clientes</a>
						</li>
					</ul>
				</li>

				<li>
					<a href="#!" class="btn-sideBar-SubMenu">
						<i class="zmdi zmdi-spellcheck zmdi-hc-fw"></i> Encuesta Personal <i class="zmdi zmdi-caret-down pull-right"></i>
					</a>
					<ul class="list-unstyled full-box">
						<li>
							<a href="{% url 'evaluacionCliente:listar_encuesta_personal' %}"><i class="zmdi zmdi-font zmdi-hc-fw"></i> Consultar Encuestas Personal</a>
						</li>
						<li>
							<a href="{% url 'evaluacionCliente:listar_respuestas_encuesta_personal' %}"><i class="zmdi zmdi-format-list-bulleted zmdi-hc-fw"></i>Consultar Resultados Encuesta</a>
						</li>
						<li>
							<a href="{% url 'evaluacionCliente:contestar_encuesta_personal' %}"><i class="zmdi zmdi-check-all zmdi-hc-fw"></i> Contestar Encuestas Personal</a>
						</li>
					</ul>
				</li>

				<li>
					<a href="#!" class="btn-sideBar-SubMenu">
						<i class="zmdi zmdi-home zmdi-hc-fw"></i> Agencia <i class="zmdi zmdi-caret-down pull-right"></i>
					</a>
					<ul class="list-unstyled full-box">
						<li>
							<a href="{% url 'evaluacionCliente:listar_agencia' %}"><i class="zmdi zmdi-balance zmdi-hc-fw"></i> Consultar Agencia </a>
						</li>
					</ul>
				</li>

				<li>
					<a href="#!" class="btn-sideBar-SubMenu">
						<i class="zmdi zmdi-view-list  zmdi-hc-fw"></i> Departamento <i class="zmdi zmdi-caret-down pull-right"></i>
					</a>
					<ul class="list-unstyled full-box">
						<li>
							<a href="{% url 'evaluacionCliente:listar_departamento' %}"><i class="zmdi zmdi-format-list-bulleted zmdi-hc-fw"></i>Consultar Departamento</a>
						</li>
					</ul>
				</li>

				<li>
					<a href="#!" class="btn-sideBar-SubMenu">
						<i class="zmdi zmdi-accounts zmdi-hc-fw"></i> Comit&eacute; <i class="zmdi zmdi-caret-down pull-right"></i>
					</a>
					<ul class="list-unstyled full-box">
						<li>
							<a href="{% url 'evaluacionCliente:listar_comite' %}"><i class="zmdi zmdi-accounts-list zmdi-hc-fw"></i>Consultar Comit&eacute;</a>
						</li>
					</ul>
				</li>

				<li>
					<a href="#!" class="btn-sideBar-SubMenu">
						<i class="zmdi zmdi-notifications zmdi-hc-fw"></i> Actividad <i class="zmdi zmdi-caret-down pull-right"></i>
					</a>
					<ul class="list-unstyled full-box">
						<li>
							<a href="{% url 'evaluacionCliente:listar_actividad' %}"><i class="zmdi zmdi-notifications-add zmdi-hc-fw"></i> Consultar Actividades </a>
						</li>
					</ul>
				</li>

			</ul>

		</div>
	</section>
{% endif %}

{% if user.is_authenticated %}
	<!-- Content page-->
	<section class="full-box dashboard-contentPage">
{% endif %}
		<!-- NavBar -->
		<nav class="full-box dashboard-Navbar">
			<ul class="full-box list-unstyled text-right" style="background-color:#049286;">
				
{% if not user.is_authenticated %}

                <li class="pull-left">
					<a onclick="location.href='{% url 'usuario:login' %}'" class="btn-menu-dashboard"><i class="zmdi zmdi-account-circle"></i></a>
				</li>

{% endif %}

                <li class="pull-left">
					<a href="#!" class="btn-menu-dashboard"><i class="zmdi zmdi-more-vert"></i></a>
				</li>

				{% comment %} 				
				<li>
					<a href="#!" class="btn-search">
						<i class="zmdi zmdi-search"></i>
					</a>
				</li> 
				{% endcomment %}

				<li>
					<a href="#!" class="btn-modal-help">
						<i class="zmdi zmdi-help-outline"></i>
					</a>
				</li>

			</ul>
		</nav>
		
        {% block content %}

            <!-- Content page -->
            <div class="container-fluid">
                <div class="page-header">
                <h1 class="text-titles" style="color:black;"><strong>Evaluaci&oacute;n de Servicio al Cliente.</strong></h1>
                </div>
            </div>

            <div class="full-box text-center" style="padding: 30px 10px;" >

                <article class="full-box tile" onclick="window.location.href='{% url 'evaluacionCliente:contestar_encuesta' %}'">
                    <div class="full-box tile-title text-center text-titles text-uppercase">
                        Encuesta
                    </div>
                    <div class="full-box tile-icon text-center">
                        <i class="zmdi zmdi-check-all" onclick="window.location.href='{% url 'evaluacionCliente:contestar_encuesta' %}'"></i>
                        </br><small>Evaluar </small>
                    </div>
                </article>

				{% comment %}
				<figure class="full-box">
                    </br>
                    </br>
                    <img src="{% static './assets/img/logo_acopus.jpg' %}" alt="UserIcon"></figure></br>
                </figure> 
                {% endcomment %}

            </div>
        
        {% endblock content %}

{% if user.is_authenticated %}
	</section>

{% endif %}	

	<!-- Dialog help -->
	<div class="modal fade" tabindex="-1" role="dialog" id="Dialog-Help">
	  	<div class="modal-dialog" role="document">
		    <div class="modal-content">

			    <div class="modal-header">
			        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
			    	<h4 class="modal-title">Ayuda</h4>
			    </div>

			    <div class="modal-body">
			        <p>
			        	Presiona el bot&oacute;n de <strong>Evaluar</strong> del area de la Encuesta para comenzar a realizarla.
			        </p>
			    </div>

		      	<div class="modal-footer">
		        	<button type="button" class="btn btn-primary btn-raised" data-dismiss="modal"><i class="zmdi zmdi-thumb-up"></i> Ok</button>
		      	</div>

		    </div>
	  	</div>
	</div>


</body>
</html>