SistemaACOPUS/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import reverse_lazy
from django.contrib.auth import views as auth_views
from .forms import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.proyecto.urls')),
    path('',include('apps.usuario.urls')),
    path('accounts/', include('django.contrib.auth.urls')),

    path('reset_password/',
         auth_views.PasswordResetView.as_view(template_name="accounts/password_reset.html"),
         name="reset_password"),

    path('reset_password_sent/', 
        auth_views.PasswordResetDoneView.as_view(template_name="accounts/password_reset_sent.html"), 
        name="password_reset_done"),

    path('reset/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(template_name="accounts/password_reset_form.html", form_class=FormularioContraOlvidada), 
        name="password_reset_confirm"),

    path('reset_password_complete/', 
        auth_views.PasswordResetCompleteView.as_view(template_name="accounts/password_reset_done.html"), 
        name="password_reset_complete"),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='accounts/password_change.html', form_class=FormularioCambioContraseña), 
        name='password_change'),

    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='accounts/password_change_done.html'), 
        name='password_change_done'),

]

'''
1 - Submit email form                         //PasswordResetView.as_view()
2 - Email sent success message                //PasswordResetDoneView.as_view()
3 - Link to password Rest form in email       //PasswordResetConfirmView.as_view()
4 - Password successfully changed message     //PasswordResetCompleteView.as_view()
5 - Password change                           //PasswordChangeDoneView.as_view()
'''

apps/proyecto/urls.py
from django.urls import path, include
from .views import *
from django.contrib.auth.decorators import login_required

from django.conf import settings
from django.conf.urls.static import static 
 
app_name = 'evaluacionCliente'

urlpatterns = [
    
    # URL de base 
    path('',index),
    path('evaluacionCliente/index/',index, name='index'),

    # URL envio de correo
    path('evaluacionCliente/send_email/<str:agencia>/<str:departamento>/<str:comite>/', login_required(enviarEmail), name='send_email'),
    path('evaluacionCliente/listar_empleado_correo/', login_required(listarEmpleadosCorreo), name='listar_empleado_correo'),        
    path('evaluacionCliente/filtrarEmpleadosCorreo/', login_required(filtrarEmpleadosCorreo), name="filtrar_empleados_correo"),
    path('evaluacionCliente/enviar_correo/<str:agencia>/<str:departamento>/<str:comite>/', login_required(enviarCorreo), name="enviar_correo"),
    path('evaluacionCliente/confirmar_invitacion/', login_required(confirmarInvitacion), name="confirmar_invitacion"),

	#URLs para Departamento
    path('evaluacionCliente/crear_departamento/', login_required(crearDepartamento), name='crear_departamento'),
    path('evaluacionCliente/listar_departamento/', login_required(listarDepartamento), name='listar_departamento'),
    path('evaluacionCliente/editar_departamento/<codigo_departamento>/', login_required(editarDepartamento), name='editar_departamento'),
    path('evaluacionCliente/eliminar_departamento/<pk>/', login_required(eliminarDepartamento.as_view()), name='eliminar_departamento'),

	#URLs para Comites
    path('evaluacionCliente/crear_comite/', login_required(crearComite), name='crear_comite'),
    path('evaluacionCliente/listar_comite/', login_required(listarComite), name='listar_comite'),
    path('evaluacionCliente/editar_comite/<id_comite>/', login_required(editarComite), name='editar_comite'),
    path('evaluacionCliente/eliminar_comite/<pk>/', login_required(eliminarComite.as_view()), name='eliminar_comite'),

	#URLs para Agenciaa
    path('evaluacionCliente/crear_agencia/', login_required(crearAgencia), name='crear_agencia'),
    path('evaluacionCliente/listar_agencia/', login_required(listarAgencia), name='listar_agencia'),    
    path('evaluacionCliente/editar_agencia/<codigo_agencia>/', login_required(editarAgencia), name='editar_agencia'),
    path('evaluacionCliente/eliminar_agencia/<pk>/', login_required(eliminarAgencia.as_view()), name='eliminar_agencia'),

    #URLs para Actividades
    path('evaluacionCliente/crear_actividad/', login_required(crearActividad), name='crear_actividad'),
    path('evaluacionCliente/listar_actividad/', login_required(listarActividad), name='listar_actividad'),    
    path('evaluacionCliente/editar_actividad/<id_actividad>/', login_required(editarActividad), name='editar_actividad'),
    path('evaluacionCliente/eliminar_actividad/<pk>/', login_required(eliminarActividad.as_view()), name='eliminar_actividad'),

    #URLs para Empleados
    path('evaluacionCliente/crear_empleado/', login_required(crearEmpleado), name='crear_empleado'),
    path('evaluacionCliente/listar_empleados/', login_required(listarEmpleados), name='listar_empleados'),    
    path('evaluacionCliente/editar_empleado/<id_empleado>/', login_required(editarEmpleado), name='editar_empleado'),
    path('evaluacionCliente/eliminar_empleado/<pk>/', login_required(eliminarEmpleado.as_view()), name='eliminar_empleado'),
    path('evaluacionCliente/filtrarEmpleados/', login_required(filtrarEmpleados), name="filtrar_empleados"),
    path('evaluacionCliente/reporteEmpleadosPDF/<str:agencia>/<str:departamento>/<str:comite>/', login_required(reporteEmpleadosPDF), name="reporte_empleadosPDF"),
    path('evaluacionCliente/exportarEmpleadosCSV/<str:agencia>/<str:departamento>/<str:comite>/', login_required(exportarEmpleados), name="reporte_empleadosCSV"),

    #URLs para Encuesta Cliente
    path('evaluacionCliente/listar_encuesta/', login_required(listarEncuesta), name='listar_encuesta'),
    path('evaluacionCliente/listar_encuesta/Agencia/', login_required(consultarAgencia), name='consultar_agencia'),
    path('evaluacionCliente/listar_encuesta/Agencia2/<str:codigoAgencia>/', login_required(consultarAgencia2), name='consultar_agencia2'),
    path('evaluacionCliente/listar_encuesta/Encuesta/<str:codigoAgencia>', login_required(consultarEncuesta), name='consultar_encuesta'),
    path('evaluacionCliente/listar_encuesta/Encuesta2/<str:codigoAgencia>/<str:tituloEncuesta>/', login_required(consultarEncuesta2), name='consultar_encuesta2'),
    path('evaluacionCliente/listar_encuesta/Preguntas/<str:codigoAgencia>/<str:tituloEncuesta>/', login_required(AgregarPreguntasEncuestaCliente), name='agregar_preguntas_encuesta_cliente'),

    path('evaluacionCliente/crear_encuesta/<str:codigoAgencia>/', login_required(crearEncuesta), name='crear_encuesta'),
    path('evaluacionCliente/editar_encuesta/<int:idEncuesta>/', login_required(editarEncuesta), name='editar_encuesta'),
    path('evaluacionCliente/eliminar_encuesta/<int:idEncuesta>/', login_required(eliminarEncuesta), name='eliminar_encuesta'),

    path('evaluacionCliente/editar_informacion_encuesta/<int:idEncuesta>/', login_required(editarInfEncuesta), name='editar_inf_encuesta'),

    path('evaluacionCliente/contestar_encuesta/', contestarEncuesta, name='contestar_encuesta'),
    path('evaluacionCliente/encuesta/Agencia/', consultarAgenciaEncuesta, name='consultar_agencia_encuesta'),
    path('evaluacionCliente/encuesta/Encuesta/<str:codigoAgencia>', consultarEncuestaCliente, name='consultar_encuesta_cliente'),
    path('evaluacionCliente/encuesta/Encuesta2/<str:codigoAgencia>', consultarEncuestaCliente2, name='consultar_encuesta2'),
    path('evaluacionCliente/encuesta/Encuesta22/<str:codigoAgencia>/<str:tituloEncuesta>', consultarEncuestaCliente22, name='consultar_encuesta22'),
    path('evaluacionCliente/encuesta/Respuesta/<str:codigoAgencia>/<str:tituloEncuesta>/<str:descripcionPregunta>/<int:contador>/', contestarEncuestaCliente, name='contestar_encuesta_cliente'),

    path('evaluacionCliente/Resultados/listar_agencia/', login_required(listarRespuestasEncuesta), name='listar_respuestas_encuesta'),
    path('evaluacionCliente/Resultados/listar_encuesta/', login_required(consultarRespuestasAgenciaCliente), name='consultar_agencia_respuestas_cliente'),
    path('evaluacionCliente/Resultados/listar_resultados/<str:codigoAgencia>', login_required(consultarRespuestasEncuestaCliente), name='consultar_respuestas_encuesta_cliente'),


    #URLs para Encuesta Personal
    path('evaluacionCliente/listar_encuesta_personal/', login_required(listarEncuestaPersonal), name='listar_encuesta_personal'),
    path('evaluacionCliente/listar_encuesta_personal/Actividad/', login_required(consultarActividadPersonal), name='consultar_actividad_personal'),
    path('evaluacionCliente/listar_encuesta_personal/Actividad2/<str:idActividad>/', login_required(consultarActividad2Personal), name='consultar_actividad2_personal'),
    path('evaluacionCliente/listar_encuesta_personal/Encuesta/<str:idActividad>', login_required(consultarEncuestaPersonal), name='consultar_encuesta_personal'),
    path('evaluacionCliente/listar_encuesta_personal/Encuesta2/<str:idActividad>/<str:tituloEncuesta>/', login_required(consultarEncuesta2Personal), name='consultar_encuesta2_personal'),
    path('evaluacionCliente/listar_encuesta_personal/Preguntas/<str:idActividad>/<str:tituloEncuesta>/', login_required(AgregarPreguntasEncuestaPersonal), name='agregar_preguntas_encuesta_personal'),

    path('evaluacionCliente/crear_encuesta_personal/<str:idActividad>/', login_required(crearEncuestaPersonal), name='crear_encuesta_personal'),
    path('evaluacionCliente/editar_encuesta_personal/<int:idEncuesta>/', login_required(editarEncuestaPersonal), name='editar_encuesta_personal'),
    path('evaluacionCliente/eliminar_encuesta_personal/<int:idEncuesta>/', login_required(eliminarEncuestaPersonal), name='eliminar_encuesta_personal'),
    
    path('evaluacionCliente/editar_informacion_encuesta_personal/<int:idEncuesta>/', login_required(editarInfEncuestaPersonal), name='editar_inf_encuesta_personal'),

    path('evaluacionCliente/contestar_encuesta_personal/', contestarEncuestaPersonal, name='contestar_encuesta_personal'),
    path('evaluacionCliente/encuestaPersonal/Actividad/', consultarActividadEncuestaDePersonal, name='consultar_actividad_encuesta_de_personal'),
    path('evaluacionCliente/encuestaPersonal/Encuesta/<str:idActividad>', consultarEncuestaDePersonal, name='consultar_encuesta_de_personal'),
    path('evaluacionCliente/encuestaPersonal/Encuesta2/<str:idActividad>', consultarEncuestaDePersonal2, name='consultar_encuesta_de_personal2'),
    path('evaluacionCliente/encuestaPersonal/Encuesta22/<str:idActividad>/<str:tituloEncuestaPersonal>', consultarEncuestaDePersonal22, name='consultar_encuesta_de_personal22'),
    path('evaluacionCliente/encuestaPersonal/Respuesta/<str:idActividad>/<str:tituloEncuesta>/<str:descripcionPregunta>/<int:contador>/', contestarEncuestaDePersonal, name='contestar_encuesta_de_personal'),

    path('evaluacionCliente/Resultados/listar_actividad/', login_required(listarRespuestasEncuestaPersonal), name='listar_respuestas_encuesta_personal'),
    path('evaluacionCliente/Resultados/listar_encuesta_personal/', login_required(consultarRespuestasActividadPersonal), name='consultar_actividad_respuestas_personal'),
    path('evaluacionCliente/Resultados/listar_resultados_encuesta/<str:idActividad>', login_required(consultarRespuestasEncuestaPersonal), name='consultar_respuestas_encuesta_personal'),

    #URLs para Reportes de Respuesta
    path('evaluacionCliente/Resultados/respuestas_encuestas_cliente/', login_required(reporteRespuestasEncuestaCliente), name='respuestas_encuestas_cliente'),

apps/usuario/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser,BaseUserManager
from apps.usuario.models import *

roles=[
    ('ADM', 'Administrador'),
]

class UsuarioManager(BaseUserManager):
    def create_user(self, email,username,nombres, apellidos, password=None):
        if not email:
            raise ValueError('El usuario debe tener un correo electronico')

        user = self.model(
            username = username,
            email = self.normalize_email(email),
            nombres = nombres,    
            apellidos=apellidos,
        )
        
        user.set_password(password)
        user.save()
        return user
    
    def create_superuser(self,username,email,nombres,apellidos, password):
        user=self.create_user(
            email,
            username = username,
            nombres = nombres,
            apellidos=apellidos,
            password=password,
        )

        user.usuario_administrador= True
        user.save()
        return user


class Usuario(AbstractBaseUser):
    username = models.CharField('Nombre de usuario',unique = True, max_length=15, blank=False)
    email = models.EmailField('Correo Electrónico', max_length=254,unique = True, blank=False)
    nombres = models.CharField('Nombres', max_length=200, null = False, blank=False)
    apellidos = models.CharField('Apellidos', max_length=200, null = False, blank=False)
    imagen = models.ImageField('Imagen de Perfil', upload_to='perfil/', max_length=200,blank = True,null = True)
    is_active = models.BooleanField(default = True)
    usuario_administrador = models.BooleanField(default = False)
    rol=models.CharField(max_length=3,null=False, blank=False,choices=roles,default='ADM')    

    objects = UsuarioManager()

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email','nombres', 'apellidos']

    def __str__(self):
        return f'{self.nombres},{self.apellidos}'

    def save(self, *args, **kwargs):

        if self.usuario_administrador == True:
            self.rol = 'ADM'

        super().save(*args, **kwargs)

    def has_perm(self, perm,obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    @property
    def is_staff(self):
        return self.usuario_administrador

SistemaACOPUS/forms.py
from django.contrib.auth.forms import SetPasswordForm, PasswordChangeForm
from django import forms
import re

class FormularioContraOlvidada(SetPasswordForm):
	new_password1=forms.CharField(label='Contraseña', widget=forms.PasswordInput(
		attrs={
			'class': 'form-control',
			'placeholder':'Ingrese su Nueva Contraseña',
			'id': 'new_password1',
			'required':'required',
		}
	))

	new_password2=forms.CharField(label='Contraseña de Confirmacion', widget=forms.PasswordInput(
		attrs={
			'class': 'form-control',
			'placeholder':'Ingrese nuevamente su Contraseña',
			'id': 'new_password2',
			'required':'required',
		}
	))

	def clean_new_password2(self):

		print(self.cleaned_data)
		new_password1=self.cleaned_data.get('new_password1')
		new_password2=self.cleaned_data.get('new_password2')
		if new_password1 != new_password2:
			raise forms.ValidationError('Contraseñas no coinciden')
		if not 8 <= len(new_password2) <= 20:
			raise forms.ValidationError('Su contraseña debe de contener entre 8 y 20 caracteres')						
		if not(re.search('[a-z]', new_password2) and re.search('[A-Z]', new_password2)):
			raise forms.ValidationError('Su contraseña debe de contener al menos una letra mayúscula y una minúscula, un número, un carácter especial, y contener entre 8 y 20 caracteres')
		if not(re.search('[0-9]', new_password2)):
			raise forms.ValidationError('Su contraseña debe de contener al menos una letra mayúscula y una minúscula, un número, un carácter especial, y contener entre 8 y 20 caracteres')
		if not(re.search('[@$%&/=?(¿¡!_.,>)<*]', new_password2)):
			raise forms.ValidationError('Su contraseña debe de contener al menos una letra mayúscula y una minúscula, un número, un carácter especial, y contener entre 8 y 20 caracteres')
		return new_password2

class FormularioCambioContraseña(PasswordChangeForm):
	new_password1=forms.CharField(label='Contraseña', widget=forms.PasswordInput(
		attrs={
			'class': 'form-control',
			'placeholder':'Ingrese su Nueva Contraseña',
			'id': 'new_password1',
			'required':'required',
		}
	))

	new_password2=forms.CharField(label='Contraseña de Confirmacion', widget=forms.PasswordInput(
		attrs={
			'class': 'form-control',
			'placeholder':'Ingrese nuevamente su Contraseña',
			'id': 'new_password2',
			'required':'required',
		}
	))

	def clean_new_password2(self):

		print(self.cleaned_data)
		new_password1=self.cleaned_data.get('new_password1')
		new_password2=self.cleaned_data.get('new_password2')
		if new_password1 != new_password2:
			raise forms.ValidationError('Contraseñas no coinciden')
		if not 8 <= len(new_password2) <= 20:
			raise forms.ValidationError('Su contraseña debe de contener entre 8 y 20 caracteres')						
		if not(re.search('[a-z]', new_password2) and re.search('[A-Z]', new_password2)):
			raise forms.ValidationError('Su contraseña debe de contener al menos una letra mayúscula y una minúscula, un número, un carácter especial, y contener entre 8 y 20 caracteres')
		if not(re.search('[0-9]', new_password2)):
			raise forms.ValidationError('Su contraseña debe de contener al menos una letra mayúscula y una minúscula, un número, un carácter especial, y contener entre 8 y 20 caracteres')
		if not(re.search('[@$%&/=?(¿¡!_.,>)<*]', new_password2)):
			raise forms.ValidationError('Su contraseña debe de contener al menos una letra mayúscula y una minúscula, un número, un carácter especial, y contener entre 8 y 20 caracteres')
		return new_password2

templates/accounts/password_change.html
{% extends 'base/base.html' %}

{% block content %}
<style type="text/css">
  .form-signin {
    width: 100%;
    max-width: 330px;
    padding: 15px;
    margin: auto;
  }
  .form-signin .checkbox {
    font-weight: 400;
  }
  .form-signin .form-control {
    position: relative;
    box-sizing: border-box;
    height: auto;
    padding: 10px;
    font-size: 16px;
  }
  .form-signin .form-control:focus {
    z-index: 2;
  }
  .form-signin input[type="password"] {
    margin-bottom: 10px;
    border-bottom-right-radius: 0;
    border-bottom-left-radius: 0;
  }
  .h3{
    text-align: center;
  }
</style>

      <font face="small fonts" size="10" color="#049286">
        <h2 align="center" class="form-titulo" style ="margin-left: 5px; margin-top:20px; bg-success text-white">Cambio de Contraseña</h2>
      </font>

<hr style="width:75%; border-color:#049286; margin-botton: 2px" >

<form method="POST" class="form-signin">{% csrf_token %}

    <input name="old_password" class="form-control" placeholder="Contraseña Anterior" type="password" id="id_old_password" required="true">
    <input name="new_password1" class="form-control" placeholder="Nueva Contraseña" type="password" id="id_new_password1" required="true">
    <input name="new_password2" class="form-control" placeholder="Confirme Nueva Contraseña" type="password" id="id_new_password2" required="true">

    {% for field in form %}
      {% for error in field.errors %}
        <p style="color: red">{{ error }}</p>
      {% endfor %}
    {% endfor %}

  <button class="btn btn-outline-success btn-lg btn-block" type="submit">Actualizar</button>  
</form>



{% endblock %}

templates/accounts/password_change_done.html
{% extends 'base/base.html' %}

{% block content %}
<body class="row justify-content-center align-items-center">

	<div class="container">
		<font face="small fonts" size="10" color="#049286">
		       <h4 align="center" class="form-titulo" style ="margin-left: 5px; margin-top:20px; bg-success text-white">Cambio de contraseña exitoso</h4>
		</font>
	</div>

	<hr style="width:75%; border-color:#049286; margin-botton: 2px" >

	<div style="width:70%; margin:auto;" align="center">
		<h3 align="center">Tu contraseña ha sido actualizada.</h3>
	</div>

</body>

{% endblock %}

templates/accounts/password_reset.html
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">

  <script src="https://code.jquery.com/jquery-3.4.1.js" integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=" crossorigin="anonymous"></script>
  <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

  <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
  <script src="https://cdn.datatables.net/1.10.16/js/dataTables.bootstrap4.min.js"></script>
  

  <!--====== Scripts -->
  <script src="https://cdn.jsdelivr.net/npm/sweetalert2@10"></script> 

{% block content %}
<style type="text/css">
  .form-signin {
    width: 100%;
    max-width: 330px;
    padding: 15px;
    margin: auto;
  }
  .form-signin .checkbox {
    font-weight: 400;
  }
  .form-signin .form-control {
    position: relative;
    box-sizing: border-box;
    height: auto;
    padding: 10px;
    font-size: 16px;
  }
  .form-signin .form-control:focus {
    z-index: 2;
  }
  .form-signin input[type="email"] {
    margin-bottom: 10px;
    border-bottom-right-radius: 0;
    border-bottom-left-radius: 0;
  }
  .h3{
    text-align: center;
  }
</style>

  <div class="container">
    <font face="small fonts" size="10" color="#049286">
           <h1 align="center" class="form-titulo" style ="margin-left: 5px; margin-top:20px; bg-success text-white">Reestablecimiento de contraseña</h1>
    </font>
  </div>

  <hr style="width:75%; border-color:#049286; margin-botton: 2px" >
  <div style="width:70%; margin:auto;" align="center">
    <h3><b>¿Olvidaste tu contraseña?</b></h3>
    <h4 align="justify">A continuaci&oacute;n escriba su correo electr&oacute;nico asociado a su cuenta, y as&iacute; enviarle instrucciones para reestablecer la contraseña.</h4>

  </div>

<form method="POST" class="form-signin">{% csrf_token %}
    <input name="email" class="form-control" placeholder="Correo Electronico" type="email" id="id_email" required="true">
  <button class="btn btn-outline-success btn-lg btn-block" type="submit">Enviar Correo</button>  
  <button class="btn btn-outline-danger btn-lg btn-block" onclick="location.href='{% url 'evaluacionCliente:index' %}'">Cancelar</button>  

</form>

{% endblock %}

templates/accounts/password_reset_done.html
{% load static %}

{% block content %}
<body class="row justify-content-center align-items-center">

	<div class="container">
		<font face="small fonts" size="10" color="#049286">
		       <h4 align="center" class="form-titulo" style ="margin-left: 5px; margin-top:20px; bg-success text-white">Reseteo de contraseña completado</h4>
		</font>
	</div>

	<hr style="width:75%; border-color:#049286; margin-botton: 2px" >

	<div style="width:70%; margin:auto;" align="center">
		<h3 align="center">Su contraseña ha sido Reestablecida. Puede continuar e iniciar sesión ahora.</h3>
		
		<a href="{% url 'login' %}">Login</a>

	</div>

</body>

{% endblock content %}

templates/accounts/password_reset_form.html
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">

  <script src="https://code.jquery.com/jquery-3.4.1.js" integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=" crossorigin="anonymous"></script>
  <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

  <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
  <script src="https://cdn.datatables.net/1.10.16/js/dataTables.bootstrap4.min.js"></script>
  

  <!--====== Scripts -->
  <script src="https://cdn.jsdelivr.net/npm/sweetalert2@10"></script> 

{% block content %}
<style type="text/css">
  .form-signin {
    width: 100%;
    max-width: 330px;
    padding: 15px;
    margin: auto;
  }
  .form-signin .checkbox {
    font-weight: 400;
  }
  .form-signin .form-control {
    position: relative;
    box-sizing: border-box;
    height: auto;
    padding: 10px;
    font-size: 16px;
  }
  .form-signin .form-control:focus {
    z-index: 2;
  }
  .form-signin input[type="password"] {
    margin-bottom: 10px;
    border-bottom-right-radius: 0;
    border-bottom-left-radius: 0;
  }
  .h3{
    text-align: center;
  }
</style>

  <div class="container">
    <font face="small fonts" size="10" color="#049286">
           <h1 align="center" class="form-titulo" style ="margin-left: 5px; margin-top:20px; bg-success text-white">Introduzca una nueva contraseña</h1>
    </font>
  </div>

  <hr style="width:75%; border-color:#049286; margin-botton: 2px" >
  <div style="width:70%; margin:auto;" align="center">

    <h4 align="justify">Por favor, Ingrese su nueva contraseña dos veces para que podamos verificar que la ingresó correctamente.</h4>
</div>

<form method="POST" class="form-signin">{% csrf_token %}

    <input name="new_password1" class="form-control" placeholder="Nueva Contraseña" type="password" id="id_new_password1" required="true">
    <input name="new_password2" class="form-control" placeholder="Confirme Nueva Contraseña" type="password" id="id_new_password2" required="true">

    {% for field in form %}
      {% for error in field.errors %}
        <p style="color: red">{{ error }}</p>
      {% endfor %}
    {% endfor %}

  <button class="btn btn-outline-success btn-lg btn-block" name="Update Password" type="submit">Resetear</button> 

</form>
{% endblock %}

templates/accounts/password_reset_sent.html
{% load static %}

{% block content %}
<body class="row justify-content-center align-items-center">

	<div class="container">
		<font face="small fonts" size="10" color="#049286">
		       <h4 align="center" class="form-titulo" style ="margin-left: 5px; margin-top:20px; bg-success text-white">Reseteo de contraseña enviado</h4>
		</font>
	</div>

	<hr style="width:75%; border-color:#049286; margin-botton: 2px" >

	<div style="width:70%; margin:auto;" align="center">
		<h3 align="justify">Le enviamos por correo electrónico instrucciones para configurar su contraseña, si existe una cuenta con el correo electrónico que ingresó. Deberías recibirlos en breve.</h3>

		<h3 align="justify">Si no recibe un correo electrónico, asegúrese de haber ingresado la dirección con la que se registró y verifique su carpeta de correo no deseado.</h3>
	</div>

</body>
{% endblock content %}