SistemaACOPUS/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import reverse_lazy
from django.contrib.auth import views as auth_views
from .forms import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.proyecto.urls')),
    path('',include('apps.usuario.urls')),
    path('accounts/', include('django.contrib.auth.urls')),

    path('reset_password/',
         auth_views.PasswordResetView.as_view(template_name="accounts/password_reset.html"),
         name="reset_password"),

    path('reset_password_sent/', 
        auth_views.PasswordResetDoneView.as_view(template_name="accounts/password_reset_sent.html"), 
        name="password_reset_done"),

    path('reset/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(template_name="accounts/password_reset_form.html", form_class=FormularioContraOlvidada), 
        name="password_reset_confirm"),

    path('reset_password_complete/', 
        auth_views.PasswordResetCompleteView.as_view(template_name="accounts/password_reset_done.html"), 
        name="password_reset_complete"),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='accounts/password_change.html', form_class=FormularioCambioContraseña), 
        name='password_change'),

    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='accounts/password_change_done.html'), 
        name='password_change_done'),

]

'''
1 - Submit email form                         //PasswordResetView.as_view()
2 - Email sent success message                //PasswordResetDoneView.as_view()
3 - Link to password Rest form in email       //PasswordResetConfirmView.as_view()
4 - Password successfully changed message     //PasswordResetCompleteView.as_view()
5 - Password change                           //PasswordChangeDoneView.as_view()
'''

apps/proyecto/urls.py
from django.urls import path, include
from .views import *
from django.contrib.auth.decorators import login_required

from django.conf import settings
from django.conf.urls.static import static 
 
app_name = 'evaluacionCliente'

urlpatterns = [
    
    # URL de base 
    path('',index),
    path('evaluacionCliente/index/',index, name='index'),

    # URL envio de correo
    path('evaluacionCliente/send_email/<str:agencia>/<str:departamento>/<str:comite>/', login_required(enviarEmail), name='send_email'),
    path('evaluacionCliente/listar_empleado_correo/', login_required(listarEmpleadosCorreo), name='listar_empleado_correo'),        
    path('evaluacionCliente/filtrarEmpleadosCorreo/', login_required(filtrarEmpleadosCorreo), name="filtrar_empleados_correo"),
    path('evaluacionCliente/enviar_correo/<str:agencia>/<str:departamento>/<str:comite>/', login_required(enviarCorreo), name="enviar_correo"),
    path('evaluacionCliente/confirmar_invitacion/', login_required(confirmarInvitacion), name="confirmar_invitacion"),

	#URLs para Departamento
    path('evaluacionCliente/crear_departamento/', login_required(crearDepartamento), name='crear_departamento'),
    path('evaluacionCliente/listar_departamento/', login_required(listarDepartamento), name='listar_departamento'),
    path('evaluacionCliente/editar_departamento/<codigo_departamento>/', login_required(editarDepartamento), name='editar_departamento'),
    path('evaluacionCliente/eliminar_departamento/<pk>/', login_required(eliminarDepartamento.as_view()), name='eliminar_departamento'),

	#URLs para Comites
    path('evaluacionCliente/crear_comite/', login_required(crearComite), name='crear_comite'),
    path('evaluacionCliente/listar_comite/', login_required(listarComite), name='listar_comite'),
    path('evaluacionCliente/editar_comite/<id_comite>/', login_required(editarComite), name='editar_comite'),
    path('evaluacionCliente/eliminar_comite/<pk>/', login_required(eliminarComite.as_view()), name='eliminar_comite'),

	#URLs para Agenciaa
    path('evaluacionCliente/crear_agencia/', login_required(crearAgencia), name='crear_agencia'),
    path('evaluacionCliente/listar_agencia/', login_required(listarAgencia), name='listar_agencia'),    
    path('evaluacionCliente/editar_agencia/<codigo_agencia>/', login_required(editarAgencia), name='editar_agencia'),
    path('evaluacionCliente/eliminar_agencia/<pk>/', login_required(eliminarAgencia.as_view()), name='eliminar_agencia'),

    #URLs para Actividades
    path('evaluacionCliente/crear_actividad/', login_required(crearActividad), name='crear_actividad'),
    path('evaluacionCliente/listar_actividad/', login_required(listarActividad), name='listar_actividad'),    
    path('evaluacionCliente/editar_actividad/<id_actividad>/', login_required(editarActividad), name='editar_actividad'),
    path('evaluacionCliente/eliminar_actividad/<pk>/', login_required(eliminarActividad.as_view()), name='eliminar_actividad'),

    #URLs para Empleados
    path('evaluacionCliente/crear_empleado/', login_required(crearEmpleado), name='crear_empleado'),
    path('evaluacionCliente/listar_empleados/', login_required(listarEmpleados), name='listar_empleados'),    
    path('evaluacionCliente/editar_empleado/<id_empleado>/', login_required(editarEmpleado), name='editar_empleado'),
    path('evaluacionCliente/eliminar_empleado/<pk>/', login_required(eliminarEmpleado.as_view()), name='eliminar_empleado'),
    path('evaluacionCliente/filtrarEmpleados/', login_required(filtrarEmpleados), name="filtrar_empleados"),
    path('evaluacionCliente/reporteEmpleadosPDF/<str:agencia>/<str:departamento>/<str:comite>/', login_required(reporteEmpleadosPDF), name="reporte_empleadosPDF"),
    path('evaluacionCliente/exportarEmpleadosCSV/<str:agencia>/<str:departamento>/<str:comite>/', login_required(exportarEmpleados), name="reporte_empleadosCSV"),

    #URLs para Encuesta Cliente
    path('evaluacionCliente/listar_encuesta/', login_required(listarEncuesta), name='listar_encuesta'),
    path('evaluacionCliente/listar_encuesta/Agencia/', login_required(consultarAgencia), name='consultar_agencia'),
    path('evaluacionCliente/listar_encuesta/Agencia2/<str:codigoAgencia>/', login_required(consultarAgencia2), name='consultar_agencia2'),
    path('evaluacionCliente/listar_encuesta/Encuesta/<str:codigoAgencia>', login_required(consultarEncuesta), name='consultar_encuesta'),
    path('evaluacionCliente/listar_encuesta/Encuesta2/<str:codigoAgencia>/<str:tituloEncuesta>/', login_required(consultarEncuesta2), name='consultar_encuesta2'),
    path('evaluacionCliente/listar_encuesta/Preguntas/<str:codigoAgencia>/<str:tituloEncuesta>/', login_required(AgregarPreguntasEncuestaCliente), name='agregar_preguntas_encuesta_cliente'),

    path('evaluacionCliente/crear_encuesta/<str:codigoAgencia>/', login_required(crearEncuesta), name='crear_encuesta'),
    path('evaluacionCliente/editar_encuesta/<int:idEncuesta>/', login_required(editarEncuesta), name='editar_encuesta'),
    path('evaluacionCliente/eliminar_encuesta/<int:idEncuesta>/', login_required(eliminarEncuesta), name='eliminar_encuesta'),

    path('evaluacionCliente/editar_informacion_encuesta/<int:idEncuesta>/', login_required(editarInfEncuesta), name='editar_inf_encuesta'),

    path('evaluacionCliente/contestar_encuesta/', contestarEncuesta, name='contestar_encuesta'),
    path('evaluacionCliente/encuesta/Agencia/', consultarAgenciaEncuesta, name='consultar_agencia_encuesta'),
    path('evaluacionCliente/encuesta/Encuesta/<str:codigoAgencia>', consultarEncuestaCliente, name='consultar_encuesta_cliente'),
    path('evaluacionCliente/encuesta/Encuesta2/<str:codigoAgencia>', consultarEncuestaCliente2, name='consultar_encuesta2'),
    path('evaluacionCliente/encuesta/Encuesta22/<str:codigoAgencia>/<str:tituloEncuesta>', consultarEncuestaCliente22, name='consultar_encuesta22'),
    path('evaluacionCliente/encuesta/Respuesta/<str:codigoAgencia>/<str:tituloEncuesta>/<str:descripcionPregunta>/<int:contador>/', contestarEncuestaCliente, name='contestar_encuesta_cliente'),

    path('evaluacionCliente/Resultados/listar_agencia/', login_required(listarRespuestasEncuesta), name='listar_respuestas_encuesta'),
    path('evaluacionCliente/Resultados/listar_encuesta/', login_required(consultarRespuestasAgenciaCliente), name='consultar_agencia_respuestas_cliente'),
    path('evaluacionCliente/Resultados/listar_resultados/<str:codigoAgencia>', login_required(consultarRespuestasEncuestaCliente), name='consultar_respuestas_encuesta_cliente'),


    #URLs para Encuesta Personal
    path('evaluacionCliente/listar_encuesta_personal/', login_required(listarEncuestaPersonal), name='listar_encuesta_personal'),
    path('evaluacionCliente/listar_encuesta_personal/Actividad/', login_required(consultarActividadPersonal), name='consultar_actividad_personal'),
    path('evaluacionCliente/listar_encuesta_personal/Actividad2/<str:idActividad>/', login_required(consultarActividad2Personal), name='consultar_actividad2_personal'),
    path('evaluacionCliente/listar_encuesta_personal/Encuesta/<str:idActividad>', login_required(consultarEncuestaPersonal), name='consultar_encuesta_personal'),
    path('evaluacionCliente/listar_encuesta_personal/Encuesta2/<str:idActividad>/<str:tituloEncuesta>/', login_required(consultarEncuesta2Personal), name='consultar_encuesta2_personal'),
    path('evaluacionCliente/listar_encuesta_personal/Preguntas/<str:idActividad>/<str:tituloEncuesta>/', login_required(AgregarPreguntasEncuestaPersonal), name='agregar_preguntas_encuesta_personal'),

    path('evaluacionCliente/crear_encuesta_personal/<str:idActividad>/', login_required(crearEncuestaPersonal), name='crear_encuesta_personal'),
    path('evaluacionCliente/editar_encuesta_personal/<int:idEncuesta>/', login_required(editarEncuestaPersonal), name='editar_encuesta_personal'),
    path('evaluacionCliente/eliminar_encuesta_personal/<int:idEncuesta>/', login_required(eliminarEncuestaPersonal), name='eliminar_encuesta_personal'),
    
    path('evaluacionCliente/editar_informacion_encuesta_personal/<int:idEncuesta>/', login_required(editarInfEncuestaPersonal), name='editar_inf_encuesta_personal'),

    path('evaluacionCliente/contestar_encuesta_personal/', contestarEncuestaPersonal, name='contestar_encuesta_personal'),
    path('evaluacionCliente/encuestaPersonal/Actividad/', consultarActividadEncuestaDePersonal, name='consultar_actividad_encuesta_de_personal'),
    path('evaluacionCliente/encuestaPersonal/Encuesta/<str:idActividad>', consultarEncuestaDePersonal, name='consultar_encuesta_de_personal'),
    path('evaluacionCliente/encuestaPersonal/Encuesta2/<str:idActividad>', consultarEncuestaDePersonal2, name='consultar_encuesta_de_personal2'),
    path('evaluacionCliente/encuestaPersonal/Encuesta22/<str:idActividad>/<str:tituloEncuestaPersonal>', consultarEncuestaDePersonal22, name='consultar_encuesta_de_personal22'),
    path('evaluacionCliente/encuestaPersonal/Respuesta/<str:idActividad>/<str:tituloEncuesta>/<str:descripcionPregunta>/<int:contador>/', contestarEncuestaDePersonal, name='contestar_encuesta_de_personal'),

    path('evaluacionCliente/Resultados/listar_actividad/', login_required(listarRespuestasEncuestaPersonal), name='listar_respuestas_encuesta_personal'),
    path('evaluacionCliente/Resultados/listar_encuesta_personal/', login_required(consultarRespuestasActividadPersonal), name='consultar_actividad_respuestas_personal'),
    path('evaluacionCliente/Resultados/listar_resultados_encuesta/<str:idActividad>', login_required(consultarRespuestasEncuestaPersonal), name='consultar_respuestas_encuesta_personal'),

    #URLs para Reportes de Respuesta
    path('evaluacionCliente/Resultados/respuestas_encuestas_cliente/', login_required(reporteRespuestasEncuestaCliente), name='respuestas_encuestas_cliente'),

templates/evaluacionCliente/agregar_preguntas_encuesta_cliente.html
{% extends 'base/base.html' %}
{% load static %}

{%block title%}
  Agregar Preguntas
{%endblock%}

{% block content %} 

	<div style="text-align:center; margin: 0 auto;">
	    <div class="container" align="center">
            </br>
            <font face="small fonts" size="10" color="#049286">
				<h2 align="center" class="form-titulo" style ="margin-left: 5px; margin-top:20px; bg-success text-white">Agregar Preguntas a Encuesta</h2>
			</font>
        </div>

	    <hr style="width:75%; border-color:#049286; margin-botton: 2px" >

        <div align="center" class="busqueda">
            <form method="POST" action="{% url 'evaluacionCliente:agregar_preguntas_encuesta_cliente' codigoAgencia tituloEncuesta %}">
                {% csrf_token %}

                <div class="col-auto p-5 text-left " style="width:60%; margin:auto;">
                    <label style ="margin-top:20px;">Agencia</label>

                    {% for i in agen %}
                        <input type="text" class="form-control" value="{{i.nombre_agencia}}" readonly>
                    {% endfor %}

                    <label style ="margin-top:20px;">Titulo Encuesta</label>
                    <input type="text" class="form-control" value="{{tituloEncuesta}}" readonly>
                    
                    <label style ="margin-top:20px;">Descripción Pregunta</label>
                    <input type="text" class="form-control" id="pregunta" name="pregunta" required minlength="5">

                    <label style ="margin-top:20px;">Visibilidad Pregunta</label></br>
                    <div class="form-check form-check-inline">
                        <input class="form-check-input" type="radio" id="visibilidad" name="visibilidad" value="S" checked>
                        <label class="form-check-label" for="inlineRadio1">Visible.</label>
                    </div>
                    <div class="form-check form-check-inline">
                        <input class="form-check-input" type="radio" id="visibilidad" name="visibilidad" value="N">
                        <label class="form-check-label" for="inlineRadio2">NO Visible.</label>
                    </div>
                    
                    <div align="center" style ="margin-top:40px;">
                        <button class="btn btn-outline-success" type="submit">Confirmar</button>
                        <button type="button" class="btn btn-outline-danger" onclick="window.location.href='{% url 'evaluacionCliente:consultar_encuesta2' codigoAgencia tituloEncuesta %}'">Cancelar</button>
                    </div>

                </div>
            </form>
        </div>
    </div>

{% endblock %}

templates/evaluacionCliente/listar_empleados_correo.html
{% extends 'base/base.html' %}
{% load static %}

{%block title%}
  Listar Empleados
{%endblock%}

{% block content %}
	<div style="text-align:center; margin: 0 auto;">
	    
	    <div class="container" align="center">
			
			<font face="small fonts" size="10" color="#049286">
				<h2 align="center" class="form-titulo" style ="margin-left: 5px; margin-top:20px; margin-bottom:1px; bg-success text-white">Listado de Empleados a enviar correo electronico de invitacion</h2>
			</font>

			{% if empleados_filtro %}

			<button class="btn btn-outline-success" onclick="location.href='{% url 'evaluacionCliente:enviar_correo' agencia departamento comite %}'">Confirmar empleados filtrados</button>

			{% endif %}


	    
		</div>

	    <!-- Boton Buscar Fech-->
	    <div align="center" class="busqueda">
	        <form method="POST"  style ="margin-top:20px;" action="{% url 'evaluacionCliente:filtrar_empleados_correo' %}">
	            {% csrf_token %} 
	            
			  <div class="form-row" style="width:95%; margin:auto;">
			    <div class="form-group col-md-4">
		            <select name="agency" class="form-control" title="Selecciona el Docente Por Favor">
		                <option selected value=""> Selecciona la Agencia </option>
		                    {% if agencias %}
		                        {% for age in agencias %}
		                            <option value="{{ age.codigo_agencia }}">{{ age.nombre_agencia }}</option>
		                        {% endfor %}
		                    {% endif %}
		                </option> 
		            </select>
			    </div>
			    <div class="form-group col-md-4">
		            <select name="depto" class="form-control" title="Selecciona el Departamento Por Favor">
		                <option selected value=""> Selecciona el Departamento </option>
		                    {% if agencias %}
		                        {% for dep in departamentos %}
		                            <option value="{{ dep.codigo_departamento }}">{{ dep.nombre_departamento }}</option>
		                        {% endfor %}
		                    {% endif %}
		                </option> 
		            </select>
			    </div>
			    <div class="form-group col-md-4">
		            <select name="comit" class="form-control input-style input-lg" title="Selecciona el Comite Por Favor">
		                <option selected value=""> Selecciona el Comite </option>
		                    {% if comites %}
		                        {% for com in comites %}
		                            <option value="{{ com.id_comite }}">{{ com.nombre_comite }}</option>
		                        {% endfor %}
		                    {% endif %}
		                </option> 
		            </select>	
			    </div>
			  </div>	            

          		<input class="btn btn-success col-2" type = "submit" value = "Filtrar Busqueda" id = "fechaBuscar"></input>

				<input class="btn btn-danger col-2" value = "Cancelar" onclick="location.href='{% url 'evaluacionCliente:listar_actividad' %}'"></input>

	        </form> 

	    </div>	

		    <div class="table-responsive">
				<table id="bootstrapdatatable" class="table table-hover" style="table-layout: fixed;">
					
					<thead>
						<tr>
							<th>Nombres</th>
							<th>Apellidos</th>	
							<th>Agencia</th>	
							<th>Departamento</th>	
							<th>C&oacute;mite</th>	
							<th>correo</th>
						</tr>
					</thead>

						<tbody>

	    		{% if empleados_filtro %}
					{% for empage in empleados_filtro %}

							<tr>
								<td>{{ empage.nombres }}</td>
								<td>{{ empage.apellidos }}</td>
								<td>{{ empage.codigo_agencia }}</td>
								<td>{{ empage.codigo_departamento }}</td>
								<td>{{ empage.id_comite }}</td>
								<td>{{ empage.email }}</td>
							</tr>

					{% endfor %}
				
				{% elif empleados %}

						{% for emp in empleados %}
							<tr>
								<td>{{ emp.nombres }}</td>
								<td>{{ emp.apellidos }}</td>
								<td>{{ emp.codigo_agencia }}</td>
								<td>{{ emp.codigo_departamento }}</td>
								<td>{{ emp.id_comite }}</td>
								<td>{{ emp.email }}</td>
							</tr>

						{% endfor %}
					</tbody>
					
				</table>
			</div>
		</div>


				{% else %}
					<h1>No existen empleados registrados, que cumplan estas condiciones</h1>
				{% endif %}


	{% block js %}

	{% endblock js %}

{% endblock content %}

templates/evaluacionCliente/listar_encuesta.html
{% extends 'base/base.html' %}

{% load static %}

{%block title%}
  Consulta de Encuestas
{%endblock%}

{% block content %}
	<div style="text-align:center; margin: 0 auto;">

<!-- ######################################################################################################################################################### -->
	<!-- VIENE DE LA VIEW  consultarEncuesta -->

	    <div class="container" align="center">
			
			<font face="small fonts" size="10" color="#049286">
				<h2 align="center" class="form-titulo" style ="margin-left: 5px; margin-top:20px; bg-success text-white">Consulta de Encuestas</h2>
			</font>

			{% if encuestasClientes %}
				
				<button class="btn btn-outline-success" onclick="location.href='{% url 'evaluacionCliente:agregar_preguntas_encuesta_cliente' codigoAgencia tituloEncuesta %}'">Agregar Preguntas</button>
				<p></p>

			{% else %}

				<p></p>			
			
			{% endif %}
	    
		</div>

<!-- ######################################################################################################################################################### -->
	<!-- VIENE DE LA VIEW  listarEncuesta -->

        <!-- Boton Buscar Agencia-->
        {% if agenciasCon %}
		
        	</br>
			<h5>Porfavor selecciona una Agencia para consultar sus Encuestas.</h5>
			</br>

			<div align="center" class="busqueda">
				<form method="POST" action="{% url 'evaluacionCliente:consultar_agencia' %}">
					{% csrf_token %} 
					<select name="codigo_agencia" id="codigo_agencia" class="form-control col-4 col-sm-3 input-style" title="Selecciona la Agencia Porfavor" required>
						<option selected value=""> Seleccione Agencia </option>
							{% for i in agenciasCon %}
								<option value="{{i.codigo_agencia}}">{{i.nombre_agencia}}</option> 
							{% endfor %}
						</option> 
					</select></br>
					<input class="btn btn-outline-success" type = "submit" value = "Buscar" id = "AgenciaBuscar">
				</form>
			</div>
		
		{% endif %}
        </br>

<!-- ######################################################################################################################################################### -->
	<!-- VIENE DE LA VIEW  consultarAgencia -->

		<!-- Boton Buscar Encuesta-->
		{% if encuestasAgencia %}

			<h5>Porfavor selecciona la Encuesta que quieres consultar.</h5>
			</br>

			<div class="table-responsive" style="width:50%; display:inline-block;">
				<table class="table table-hover text-center">
					
					<thead>
						<tr>
							<th class="text-center" style="color:#049286"><strong>Agencia:</strong></th>
							{% for i in nombreAgencia%}
								<th class="text-center"><i>{{ i.nombre_agencia }}</i></th>
							{% endfor %}
						</tr>
					</thead>

				</table>
			</div>

			</br></br>
		
			<div align="center" class="busqueda">
				<form method="POST" action="{% url 'evaluacionCliente:consultar_encuesta' codAgencia %}">
					{% csrf_token %} 
					<select name="titulo_encuesta" id="titulo_encuesta" class="form-control col-4 col-sm-3 input-style" title="Selecciona la Encuesta a Consultar" required>
						<option selected value=""> Seleccione la Encuesta </option>
							{% for i in encuestasAgencia %}
								<option value="{{i.titulo_encuesta_cliente}}">{{i.titulo_encuesta_cliente}}</option> 
							{% endfor %}
						</option> 
					</select></br>
					<input class="btn btn-outline-success" type = "submit" value = "Buscar" id = "AgenciaBuscar"></br>
				</form>
			</div>

			</br></br></br>
			<h5>Si no encuentras la Encuesta que buscas,</br> puedes crear una tu mismo.</h5>
			</br>
			<button type="button" class="btn btn-outline-success" onclick="window.location.href='{% url 'evaluacionCliente:crear_encuesta' codAgencia %}'">Crear Encuesta</button>

		{% else %}

			{% if codigo_agencia %}

				<div class="table-responsive" style="width:50%; display:inline-block;">
					<table class="table table-hover text-center">
						
						<thead>
							<tr>
								<th class="text-center" style="color:#049286"><strong>Agencia:</strong></th>
								{% for i in nombreAgencia%}
									<th class="text-center"><i>{{ i.nombre_agencia }}</i></th>
								{% endfor %}
							</tr>
						</thead>

					</table>
				</div>

				</br></br></br>
				<h5>Si no encuentras la Encuesta que buscas,</br> puedes crear una tu mismo.</h5>
				</br>
				<button type="button" class="btn btn-outline-success" onclick="window.location.href='{% url 'evaluacionCliente:crear_encuesta' codAgencia %}'">Crear Encuesta</button>
			
			{% endif %}

		{% endif %}
        </br>

<!-- ######################################################################################################################################################### -->
	<!-- VIENE DE LA VIEW  consultarEncuesta -->

		{% if encuestasClientes %}

			<div class="table-responsive" style="width:60%; display:inline-block;">
				<table class="table table-hover text-center">
					
					<thead>
						<tr>
							<th class="text-center" style="color:#049286">Agencia</th>
							<th class="text-center" style="color:#049286">Título Encuesta</th>
							<th class="text-center" style="color:#049286">Desde</th>
							<th class="text-center" style="color:#049286">Hasta</th>
						</tr>
					</thead>

					<tbody>
						<tr>
							<td><strong>{{ nombreAgencia }}</strong></td>
							<td><strong><i><a style="color:black;" href="{% url 'evaluacionCliente:editar_inf_encuesta' idCl %}">{{ tituloEncuesta }}</a></i></strong></td>
							<td><strong><i><a style="color:black;" href="{% url 'evaluacionCliente:editar_inf_encuesta' idCl %}">{{ desde }}</a></i></strong></td>
							{% ifequal hasta None %}
								<td><strong><i><a style="color:black;" href="{% url 'evaluacionCliente:editar_inf_encuesta' idCl %}"> - </a></i></strong></td>
							{% else %}
								<td><strong><i><a style="color:black;" href="{% url 'evaluacionCliente:editar_inf_encuesta' idCl %}">{{ hasta }}</a></i></strong></td>
							{% endifequal %}
						</tr>
					</tbody>

				</table>
			</div>


		    <div class="table-responsive" style="width:93%; display:inline-block;">
				<table id="bootstrapdatatable" class="table table-hover">
					<thead>
						<tr>
							<th>Descripción de la Pregunta</th>	
							<th>Visibilidad de la Pregunta</th>
							<th>Opción</th>
						</tr>
					</thead>

					<tbody>
						{% for enc in encuestasClientes %}
							<tr>
                                <td>{{ enc.descripcion_pregunta }}</td>	
								{% ifequal enc.visibilidad_pregunta_cliente 'S' %}
                                	<td>Visible al usuario.</td>
								{% else %}
									<td>NO Visible al usuario.</td>	
								{% endifequal %}
								<td>
									<button type="button" class="btn btn-primary btn-sm tableButton"  onclick="location.href='{% url 'evaluacionCliente:editar_encuesta' enc.id %}'" style="color:white;"> Editar </button>
									<button type="button" class="btn btn-danger tableButton  btn-sm" data-toggle="modal" data-target="#a{{ enc.id }}">Eliminar</button>
								</td>					
							</tr>

							<div class="modal fade" id="a{{ enc.id }}" tabindex="-1" role="dialog" aria-labelledBy="fm-modal-grid" aria-hidden="true">
							    <div class="modal-dialog modal-lg">
							        <div class="modal-content">
								        
										<div class="modal-header">
											<i>Eliminaci&oacute;n de la pregunta:</i> <strong> {{ enc.descripcion_pregunta }} </strong>
								            <button type="button" class="close" data-dismiss="modal">&times;</button>
								        </div>
							            
										<div class="modal-body">
									        <div class="modal-body text-center" >
									            <h4><i>¿Realmente desea eliminar la pregunta</i> <strong> {{ enc.descripcion_pregunta }} </strong> <i>de la Encuesta?</i></h4>
									        </div>							            
							            
											<div class="modal-footer">
												<form action="{% url 'evaluacionCliente:eliminar_encuesta' enc.id %}" method="POST">
													{% csrf_token %}
													<button class="btn btn-danger" data-align="right"><strong>Confirmar</strong></button>
												</form>
												<button class="btn btn-primary" data-dismiss="modal"><strong>Cancelar</strong></button>
											</div>
										</div>

							    	</div>
								</div>
							</div>
							
						{% endfor %}
					</tbody>

				</table>
			</div>
		{% endif %}
	</div>

	{% block js %}

	{% endblock js %}

{% endblock content %}